/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaSistema.java
 *
 * Created on 04/05/2010, 22:52:24
 */
package premoldados;

import javax.swing.JFrame;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import Banco.Conexao;
import Telacadastros.TelaCidade;
import Telacadastros.TelaClassifica;
import Telacadastros.TelaCliente;
import Telacadastros.TelaColaborador;
import Telacadastros.TelaComposicao;
import Telacadastros.TelaCustos;
import Telacadastros.TelaDepartamento;
import Telacadastros.TelaEstado;
import Telacadastros.TelaFornecedor;
import Telacadastros.TelaFuncao;
import Telacadastros.TelaMateriaPrima;
import Telacadastros.TelaMaterial;
import Telacadastros.TelaOrdem;
import Telacadastros.TelaPontuacao;
import Telacadastros.TelaProduto;
import Telacadastros.TelaUnidades;
import Telacadastros.TelaVeiculos;

import relatorios.RelClientes;
import relatorios.RelCompras;
import relatorios.RelCtaPagar;
import relatorios.RelCtaReceber;
import relatorios.RelEstoque;
import relatorios.RelFornecedores;
import relatorios.RelMateriaPrima;
import relatorios.RelProduca;
import relatorios.RelProdutos;
import relatorios.RelVendas;
import telaMovimenacao.AbriCaixa;

import telaMovimenacao.TelaCaixa;
import telaMovimenacao.TelaCompra;
import telaMovimenacao.TelaContaPagar;
import telaMovimenacao.TelaContaReceber;
import telaMovimenacao.TelaCotacao;
import telaMovimenacao.TelaPagamento;
import telaMovimenacao.TelaPedCompra;

import telaMovimenacao.TelaPedVenda;
import telaMovimenacao.TelaRecebimento;
import telaMovimenacao.TelaVenda;

/**
 *
 * @author chs
 */
public class TelaSistema extends javax.swing.JFrame implements InternalFrameListener {

    TelaEstado telaestado;
    TelaCidade telacidade;
    TelaCliente telacliente;
    TelaClassifica telaclassifica;
    TelaPontuacao telapontuacao;
    TelaFornecedor telafornecedor;
    TelaUnidades telaunidades;
    TelaMateriaPrima telamatprima;
    TelaDepartamento teladepartamento;
    TelaFuncao telafuncao;
    TelaColaborador telacolab;
    TelaVeiculos telaveiculo;
    TelaCustos telacustos;
    TelaMaterial telamaterial;
    TelaComposicao telacomposicao;
    TelaProduto telaproduto;
    TelaCotacao telacotacao;
    TelaPedVenda pedidovenda;
    TelaVenda telavenda;
    TelaPedCompra telapedcompra;
    TelaCompra telacompra;
    TelaContaReceber telacontareceber;
    TelaRecebimento telarecebimnento;
    TelaContaPagar telacontapagar;
    TelaPagamento telapagamento;
    TelaCaixa telacaixa;
    TelaOrdem telaordem;
    RelClientes relclientes;
    RelFornecedores relfornecedores;
    RelMateriaPrima relmatprima;
    RelProdutos relprodutos;
    RelCompras relcompras;
    RelVendas relvendas;
    RelProduca relproducao;
    RelCtaPagar relctapagar;
    RelCtaReceber relctareceber;
    RelEstoque relestoque;
    AbriCaixa abrircaixa;

    /** Creates new form TelaSistema */
    public TelaSistema() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
       // Conexao.getConexao();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdp = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuCadstro = new javax.swing.JMenu();
        jMenuLocalizacoes = new javax.swing.JMenu();
        jMenuCidade = new javax.swing.JMenuItem();
        jMenuItemEstado = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuCadCliente = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuFornecedores = new javax.swing.JMenu();
        jMenuCadForn = new javax.swing.JMenuItem();
        jMenuClassificacao = new javax.swing.JMenuItem();
        jMenuPontuacao = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuMateriaPrimaUnd = new javax.swing.JMenu();
        jMenuItemUnidades = new javax.swing.JMenuItem();
        jMenuItemCadMat = new javax.swing.JMenuItem();
        jMenuItemTipoMat = new javax.swing.JMenuItem();
        jMenuItemCustos = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuCadProd = new javax.swing.JMenu();
        jMenuItemComposicoes = new javax.swing.JMenuItem();
        jMenuItemCadProd = new javax.swing.JMenuItem();
        jMenuMovimento = new javax.swing.JMenu();
        jMenuCompras = new javax.swing.JMenu();
        jMenuItemPedidoCompra = new javax.swing.JMenuItem();
        jMenuItemLancaCompra = new javax.swing.JMenuItem();
        jMenuItemCotacoes = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuVendas = new javax.swing.JMenu();
        jMenuItemedVendas = new javax.swing.JMenuItem();
        jMenuItemFinVendas = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuProducao = new javax.swing.JMenu();
        jMenuItemOdemProd = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuContPagar = new javax.swing.JMenu();
        jMenuItemLancPagar = new javax.swing.JMenuItem();
        jMenuItemPag = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuContasRec = new javax.swing.JMenu();
        jMenuItemLancRec = new javax.swing.JMenuItem();
        jMenuItemRecb = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuCaixa = new javax.swing.JMenu();
        jMenuItemMovCaixa = new javax.swing.JMenuItem();
        jMenuItemAbriCaixa = new javax.swing.JMenuItem();
        jMenuRelario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ACA - Controle Empresarial");

        jdp.setBackground(java.awt.SystemColor.controlLtHighlight);

        jButton1.setText("sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(0, 0, -1, -1);
        jdp.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuCadstro.setText("Cadastros");

        jMenuLocalizacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/browser.png"))); // NOI18N
        jMenuLocalizacoes.setText("Localizações");

        jMenuCidade.setText("Cadastro de Cidades");
        jMenuCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCidadeActionPerformed(evt);
            }
        });
        jMenuLocalizacoes.add(jMenuCidade);

        jMenuItemEstado.setText("Cadastro de Estados");
        jMenuItemEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEstadoActionPerformed(evt);
            }
        });
        jMenuLocalizacoes.add(jMenuItemEstado);

        jMenuCadstro.add(jMenuLocalizacoes);
        jMenuCadstro.add(jSeparator2);

        jMenuCadCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/personal.png"))); // NOI18N
        jMenuCadCliente.setText("Clientes");

        jMenuCliente.setText("Cadastro de Clientes");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenuCadCliente.add(jMenuCliente);

        jMenuCadstro.add(jMenuCadCliente);
        jMenuCadstro.add(jSeparator3);

        jMenuFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Community Help.png"))); // NOI18N
        jMenuFornecedores.setText("Fornecedores");

        jMenuCadForn.setText("Cadastro de Fornecedores");
        jMenuCadForn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadFornActionPerformed(evt);
            }
        });
        jMenuFornecedores.add(jMenuCadForn);

        jMenuClassificacao.setText("Classificação");
        jMenuClassificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClassificacaoActionPerformed(evt);
            }
        });
        jMenuFornecedores.add(jMenuClassificacao);

        jMenuPontuacao.setText("Pontuações");
        jMenuPontuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPontuacaoActionPerformed(evt);
            }
        });
        jMenuFornecedores.add(jMenuPontuacao);

        jMenuCadstro.add(jMenuFornecedores);
        jMenuCadstro.add(jSeparator1);

        jMenuMateriaPrimaUnd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/kthememgr.png"))); // NOI18N
        jMenuMateriaPrimaUnd.setText("Materia Prima");

        jMenuItemUnidades.setText("Unidades e Dimensões");
        jMenuItemUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUnidadesActionPerformed(evt);
            }
        });
        jMenuMateriaPrimaUnd.add(jMenuItemUnidades);

        jMenuItemCadMat.setText("Materias Primas");
        jMenuItemCadMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMatActionPerformed(evt);
            }
        });
        jMenuMateriaPrimaUnd.add(jMenuItemCadMat);

        jMenuItemTipoMat.setText("Tipo de material");
        jMenuItemTipoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTipoMatActionPerformed(evt);
            }
        });
        jMenuMateriaPrimaUnd.add(jMenuItemTipoMat);

        jMenuItemCustos.setText("Custos");
        jMenuItemCustos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCustosActionPerformed(evt);
            }
        });
        jMenuMateriaPrimaUnd.add(jMenuItemCustos);

        jMenuCadstro.add(jMenuMateriaPrimaUnd);
        jMenuCadstro.add(jSeparator4);

        jMenuCadProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/warehause.png"))); // NOI18N
        jMenuCadProd.setText("Produtos");

        jMenuItemComposicoes.setText("Composições");
        jMenuItemComposicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemComposicoesActionPerformed(evt);
            }
        });
        jMenuCadProd.add(jMenuItemComposicoes);

        jMenuItemCadProd.setText("Cadastro de Produtos");
        jMenuItemCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadProdActionPerformed(evt);
            }
        });
        jMenuCadProd.add(jMenuItemCadProd);

        jMenuCadstro.add(jMenuCadProd);

        jMenuBar.add(jMenuCadstro);

        jMenuMovimento.setText("Movimentos");

        jMenuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ark.png"))); // NOI18N
        jMenuCompras.setText("Compras");

        jMenuItemPedidoCompra.setText("Pedido de Compra");
        jMenuItemPedidoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPedidoCompraActionPerformed(evt);
            }
        });
        jMenuCompras.add(jMenuItemPedidoCompra);

        jMenuItemLancaCompra.setText("Finalizar Compras");
        jMenuItemLancaCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLancaCompraActionPerformed(evt);
            }
        });
        jMenuCompras.add(jMenuItemLancaCompra);

        jMenuItemCotacoes.setText("Cotações");
        jMenuItemCotacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCotacoesActionPerformed(evt);
            }
        });
        jMenuCompras.add(jMenuItemCotacoes);

        jMenuMovimento.add(jMenuCompras);
        jMenuMovimento.add(jSeparator7);

        jMenuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/blockdevice.png"))); // NOI18N
        jMenuVendas.setText("Vendas");

        jMenuItemedVendas.setText("Pedido  de Vendas");
        jMenuItemedVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemedVendasActionPerformed(evt);
            }
        });
        jMenuVendas.add(jMenuItemedVendas);

        jMenuItemFinVendas.setText("Finalizar Vendas");
        jMenuItemFinVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFinVendasActionPerformed(evt);
            }
        });
        jMenuVendas.add(jMenuItemFinVendas);

        jMenuMovimento.add(jMenuVendas);
        jMenuMovimento.add(jSeparator8);

        jMenuProducao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/kded.png"))); // NOI18N
        jMenuProducao.setText("Produção");

        jMenuItemOdemProd.setText("Ordem de Produção");
        jMenuItemOdemProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOdemProdActionPerformed(evt);
            }
        });
        jMenuProducao.add(jMenuItemOdemProd);

        jMenuMovimento.add(jMenuProducao);
        jMenuMovimento.add(jSeparator9);

        jMenuContPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buisness.png"))); // NOI18N
        jMenuContPagar.setText("Contas a Pagar ");

        jMenuItemLancPagar.setText("Lançamento");
        jMenuItemLancPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLancPagarActionPerformed(evt);
            }
        });
        jMenuContPagar.add(jMenuItemLancPagar);

        jMenuItemPag.setText("Pagamento");
        jMenuItemPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPagActionPerformed(evt);
            }
        });
        jMenuContPagar.add(jMenuItemPag);

        jMenuMovimento.add(jMenuContPagar);
        jMenuMovimento.add(jSeparator13);

        jMenuContasRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gadu.png"))); // NOI18N
        jMenuContasRec.setText("Contas a Receber");

        jMenuItemLancRec.setText("Lançamento");
        jMenuItemLancRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLancRecActionPerformed(evt);
            }
        });
        jMenuContasRec.add(jMenuItemLancRec);

        jMenuItemRecb.setText("Recebimento");
        jMenuItemRecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRecbActionPerformed(evt);
            }
        });
        jMenuContasRec.add(jMenuItemRecb);

        jMenuMovimento.add(jMenuContasRec);
        jMenuMovimento.add(jSeparator14);

        jMenuCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/kpaint.png"))); // NOI18N
        jMenuCaixa.setText("Caixa");

        jMenuItemMovCaixa.setText("Movimento");
        jMenuItemMovCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMovCaixaActionPerformed(evt);
            }
        });
        jMenuCaixa.add(jMenuItemMovCaixa);

        jMenuItemAbriCaixa.setText("Abertura e Fechamento ");
        jMenuItemAbriCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbriCaixaActionPerformed(evt);
            }
        });
        jMenuCaixa.add(jMenuItemAbriCaixa);

        jMenuMovimento.add(jMenuCaixa);

        jMenuBar.add(jMenuMovimento);

        jMenuRelario.setText("Relatorios");

        jMenuItem1.setText("Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuRelario.add(jMenuItem1);
        jMenuRelario.add(jSeparator5);

        jMenuItem2.setText("Fornecedor");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuRelario.add(jMenuItem2);
        jMenuRelario.add(jSeparator6);

        jMenuItem3.setText("Materia Prima");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuRelario.add(jMenuItem3);
        jMenuRelario.add(jSeparator10);

        jMenuItem4.setText("Produtos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuRelario.add(jMenuItem4);
        jMenuRelario.add(jSeparator11);

        jMenuItem5.setText("Compra");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuRelario.add(jMenuItem5);
        jMenuRelario.add(jSeparator15);

        jMenuItem6.setText("Vendas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuRelario.add(jMenuItem6);
        jMenuRelario.add(jSeparator12);

        jMenuItem7.setText("Produção");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenuRelario.add(jMenuItem7);
        jMenuRelario.add(jSeparator16);

        jMenuItem8.setText("Contas a pagar");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuRelario.add(jMenuItem8);
        jMenuRelario.add(jSeparator17);

        jMenuItem9.setText("Contas a receber");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuRelario.add(jMenuItem9);
        jMenuRelario.add(jSeparator18);

        jMenuItem10.setText("Estoque");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenuRelario.add(jMenuItem10);

        jMenuBar.add(jMenuRelario);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp, javax.swing.GroupLayout.DEFAULT_SIZE, 1540, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdp, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPedidoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPedidoCompraActionPerformed
        if (telapedcompra == null) {
            telapedcompra = new TelaPedCompra();
            telapedcompra.addInternalFrameListener(this);
            jdp.add(telapedcompra);
            telapedcompra.setVisible(true);
        }
        jdp.moveToFront(telapedcompra);

    }//GEN-LAST:event_jMenuItemPedidoCompraActionPerformed

    private void jMenuItemedVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemedVendasActionPerformed
        if (pedidovenda == null) {
            pedidovenda = new TelaPedVenda();
            pedidovenda.addInternalFrameListener(this);
            jdp.add(pedidovenda);
            pedidovenda.setVisible(true);
        }
        jdp.moveToFront(pedidovenda);

    }//GEN-LAST:event_jMenuItemedVendasActionPerformed

    private void jMenuItemFinVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFinVendasActionPerformed
        if (telavenda == null) {
            telavenda = new TelaVenda();
            telavenda.addInternalFrameListener(this);
            jdp.add(telavenda);
            telavenda.setVisible(true);
        }
        jdp.moveToFront(telavenda);
    }//GEN-LAST:event_jMenuItemFinVendasActionPerformed

    private void jMenuItemCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadProdActionPerformed
        if (telaproduto == null) {
            telaproduto = new TelaProduto();
            telaproduto.addInternalFrameListener(this);
            jdp.add(telaproduto);
            telaproduto.setVisible(true);
        }
        jdp.moveToFront(telaproduto);
}//GEN-LAST:event_jMenuItemCadProdActionPerformed

    private void jMenuItemComposicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemComposicoesActionPerformed
        if (telacomposicao == null) {
            telacomposicao = new TelaComposicao();
            telacomposicao.addInternalFrameListener(this);
            jdp.add(telacomposicao);
            telacomposicao.setVisible(true);
        }
        jdp.moveToFront(telacomposicao);
}//GEN-LAST:event_jMenuItemComposicoesActionPerformed

    private void jMenuItemCustosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCustosActionPerformed
        if (telacustos == null) {
            telacustos = new TelaCustos();
            telacustos.addInternalFrameListener(this);
            jdp.add(telacustos);
            telacustos.setVisible(true);
        }
        jdp.moveToFront(telacustos);
}//GEN-LAST:event_jMenuItemCustosActionPerformed

    private void jMenuItemTipoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTipoMatActionPerformed
        if (telamaterial == null) {
            telamaterial = new TelaMaterial();
            telamaterial.addInternalFrameListener(this);
            jdp.add(telamaterial);
            telamaterial.setVisible(true);
        }
        jdp.moveToFront(telamaterial);
}//GEN-LAST:event_jMenuItemTipoMatActionPerformed

    private void jMenuItemCadMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMatActionPerformed
        if (telamatprima == null) {
            telamatprima = new TelaMateriaPrima();
            telamatprima.addInternalFrameListener(this);
            jdp.add(telamatprima);
            telamatprima.setVisible(true);
        }
        jdp.moveToFront(telamatprima);
}//GEN-LAST:event_jMenuItemCadMatActionPerformed

    private void jMenuItemUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUnidadesActionPerformed
        if (telaunidades == null) {
            telaunidades = new TelaUnidades();
            telaunidades.addInternalFrameListener(this);
            jdp.add(telaunidades);
            telaunidades.setVisible(true);
        }
        jdp.moveToFront(telaunidades);
    }//GEN-LAST:event_jMenuItemUnidadesActionPerformed

    private void jMenuPontuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPontuacaoActionPerformed
        if (telapontuacao == null) {
            telapontuacao = new TelaPontuacao();
            telapontuacao.addInternalFrameListener(this);
            jdp.add(telapontuacao);
            telapontuacao.setVisible(true);
        }
        jdp.moveToFront(telapontuacao);
}//GEN-LAST:event_jMenuPontuacaoActionPerformed

    private void jMenuClassificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClassificacaoActionPerformed
        if (telaclassifica == null) {
            telaclassifica = new TelaClassifica();
            telaclassifica.addInternalFrameListener(this);
            jdp.add(telaclassifica);
            telaclassifica.setVisible(true);
            //telaestado.setSize(800, 300);
        }
        jdp.moveToFront(telaclassifica);
}//GEN-LAST:event_jMenuClassificacaoActionPerformed

    private void jMenuCadFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadFornActionPerformed
        if (telafornecedor == null) {
            telafornecedor = new TelaFornecedor();
            telafornecedor.addInternalFrameListener(this);
            jdp.add(telafornecedor);
            telafornecedor.setVisible(true);
        }
        jdp.moveToFront(telafornecedor);
}//GEN-LAST:event_jMenuCadFornActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        if (telacliente == null) {
            telacliente = new TelaCliente();
            telacliente.addInternalFrameListener(this);
            jdp.add(telacliente);
            telacliente.setVisible(true);

        }
        jdp.moveToFront(telacliente);
}//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuItemEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstadoActionPerformed
        if (telaestado == null) {
            telaestado = new TelaEstado();
            telaestado.addInternalFrameListener(this);
            jdp.add(telaestado);
            telaestado.setVisible(true);
            //telaestado.setSize(800, 300);
        }
        jdp.moveToFront(telaestado);
}//GEN-LAST:event_jMenuItemEstadoActionPerformed

    private void jMenuCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCidadeActionPerformed
        if (telacidade == null) {
            telacidade = new TelaCidade();
            telacidade.addInternalFrameListener(this);
            jdp.add(telacidade);
            //telacidade.setSize(800, 300);
            telacidade.setVisible(true);
        }
        jdp.moveToFront(telacidade);
}//GEN-LAST:event_jMenuCidadeActionPerformed

    private void jMenuItemCotacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCotacoesActionPerformed
        if (telacotacao == null) {
            telacotacao = new TelaCotacao();
            telacotacao.addInternalFrameListener(this);
            jdp.add(telacotacao);
            //telacidade.setSize(800, 300);
            telacotacao.setVisible(true);
        }
        jdp.moveToFront(telacotacao);
    }//GEN-LAST:event_jMenuItemCotacoesActionPerformed

    private void jMenuItemLancaCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLancaCompraActionPerformed
        if (telacompra == null) {
            telacompra = new TelaCompra();
            telacompra.addInternalFrameListener(this);
            jdp.add(telacompra);
            //telacidade.setSize(800, 300);
            telacompra.setVisible(true);
        }
        jdp.moveToFront(telacompra);
    }//GEN-LAST:event_jMenuItemLancaCompraActionPerformed

    private void jMenuItemLancPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLancPagarActionPerformed
        if (telacontapagar == null) {
            telacontapagar = new TelaContaPagar();
            telacontapagar.addInternalFrameListener(this);
            jdp.add(telacontapagar);
            //telacidade.setSize(800, 300);
            telacontapagar.setVisible(true);
        }
        jdp.moveToFront(telacontapagar);
    }//GEN-LAST:event_jMenuItemLancPagarActionPerformed

    private void jMenuItemLancRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLancRecActionPerformed
        if (telacontareceber == null) {
            telacontareceber = new TelaContaReceber();
            telacontareceber.addInternalFrameListener(this);
            jdp.add(telacontareceber);
            //telacidade.setSize(800, 300);
            telacontareceber.setVisible(true);
        }
        jdp.moveToFront(telacontareceber);
    }//GEN-LAST:event_jMenuItemLancRecActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemRecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRecbActionPerformed
        if (telarecebimnento == null) {
            telarecebimnento = new TelaRecebimento();
            telarecebimnento.addInternalFrameListener(this);
            jdp.add(telarecebimnento);
            //telacidade.setSize(800, 300);
            telarecebimnento.setVisible(true);
        }
        jdp.moveToFront(telarecebimnento);
    }//GEN-LAST:event_jMenuItemRecbActionPerformed

    private void jMenuItemPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPagActionPerformed
        if (telapagamento == null) {
            telapagamento = new TelaPagamento();
            telapagamento.addInternalFrameListener(this);
            jdp.add(telapagamento);
            //telacidade.setSize(800, 300);
            telapagamento.setVisible(true);
        }
        jdp.moveToFront(telapagamento);
    }//GEN-LAST:event_jMenuItemPagActionPerformed

    private void jMenuItemMovCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMovCaixaActionPerformed
        if (telacaixa == null) {
            telacaixa = new TelaCaixa();
            telacaixa.addInternalFrameListener(this);
            jdp.add(telacaixa);
            //telacidade.setSize(800, 300);
            telacaixa.setVisible(true);
        }
        jdp.moveToFront(telacaixa);
    }//GEN-LAST:event_jMenuItemMovCaixaActionPerformed

    private void jMenuItemOdemProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOdemProdActionPerformed
        if (telaordem == null) {
            telaordem = new TelaOrdem();
            telaordem.addInternalFrameListener(this);
            jdp.add(telaordem);
            //telacidade.setSize(800, 300);
            telaordem.setVisible(true);
        }
        jdp.moveToFront(telaordem);
    }//GEN-LAST:event_jMenuItemOdemProdActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (relclientes == null) {
            relclientes = new RelClientes();
            relclientes.addInternalFrameListener(this);
            jdp.add(relclientes);
            //telacidade.setSize(800, 300);
            relclientes.setVisible(true);
        }
        jdp.moveToFront(relclientes);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if (relfornecedores == null) {
            relfornecedores = new RelFornecedores();
            relfornecedores.addInternalFrameListener(this);
            jdp.add(relfornecedores);
            //telacidade.setSize(800, 300);
            relfornecedores.setVisible(true);
        }
        jdp.moveToFront(relfornecedores);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (relmatprima == null) {
            relmatprima = new RelMateriaPrima();
            relmatprima.addInternalFrameListener(this);
            jdp.add(relmatprima);
            //telacidade.setSize(800, 300);
            relmatprima.setVisible(true);
        }
        jdp.moveToFront(relmatprima);


    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        if (relprodutos == null) {
            relprodutos = new RelProdutos();
            relprodutos.addInternalFrameListener(this);
            jdp.add(relprodutos);
            //telacidade.setSize(800, 300);
            relprodutos.setVisible(true);
        }
        jdp.moveToFront(relprodutos);


    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (relcompras == null) {
            relcompras = new RelCompras();
            relcompras.addInternalFrameListener(this);
            jdp.add(relcompras);
            //telacidade.setSize(800, 300);
            relcompras.setVisible(true);
        }
        jdp.moveToFront(relcompras);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        if (relestoque == null) {
            relestoque = new RelEstoque();
            relestoque.addInternalFrameListener(this);
            jdp.add(relestoque);
            //telacidade.setSize(800, 300);
            relestoque.setVisible(true);
        }
        jdp.moveToFront(relestoque);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (relvendas == null) {
            relvendas = new RelVendas();
            relvendas.addInternalFrameListener(this);
            jdp.add(relvendas);
            //telacidade.setSize(800, 300);
            relvendas.setVisible(true);
        }
        jdp.moveToFront(relvendas);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        if (relproducao == null) {
            relproducao = new RelProduca();
            relproducao.addInternalFrameListener(this);
            jdp.add(relproducao);
            //telacidade.setSize(800, 300);
            relproducao.setVisible(true);
        }
        jdp.moveToFront(relproducao);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        if (relctapagar == null) {
            relctapagar = new RelCtaPagar();
            relctapagar.addInternalFrameListener(this);
            jdp.add(relctapagar);
            //telacidade.setSize(800, 300);
            relctapagar.setVisible(true);
        }
        jdp.moveToFront(relctapagar);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        if (relctareceber == null) {
            relctareceber = new RelCtaReceber();
            relctareceber.addInternalFrameListener(this);
            jdp.add(relctareceber);
            //telacidade.setSize(800, 300);
            relctareceber.setVisible(true);
        }
        jdp.moveToFront(relctareceber);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItemAbriCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbriCaixaActionPerformed
        if (abrircaixa == null) {
            abrircaixa = new AbriCaixa();
            abrircaixa.addInternalFrameListener(this);
            jdp.add(abrircaixa);
            //telacidade.setSize(800, 300);
            abrircaixa.setVisible(true);
        }
        jdp.moveToFront(abrircaixa);
    }//GEN-LAST:event_jMenuItemAbriCaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

    public void run() {
    new TelaSistema().setVisible(true);
    }
    });
    }*/
    public void internalFrameOpened(InternalFrameEvent e) {
    }

    public void internalFrameClosing(InternalFrameEvent e) {
    }

    public void internalFrameClosed(InternalFrameEvent e) {
        if (e.getSource() == telacidade) {
            telacidade = null;
        }
        if (e.getSource() == telaestado) {
            telaestado = null;
        }
        if (e.getSource() == telacliente) {
            telacliente = null;
        }
        if (e.getSource() == telaclassifica) {
            telaclassifica = null;
        }
        if (e.getSource() == telafornecedor) {
            telafornecedor = null;
        }
        if (e.getSource() == telapontuacao) {
            telapontuacao = null;
        }
        if (e.getSource() == telaunidades) {
            telapontuacao = null;
        }
        if (e.getSource() == telamatprima) {
            telamatprima = null;
        }
        if (e.getSource() == telamaterial) {
            telamaterial = null;
        }
        if (e.getSource() == teladepartamento) {
            teladepartamento = null;
        }
        if (e.getSource() == telafuncao) {
            telafuncao = null;
        }
        if (e.getSource() == telacolab) {
            telacolab = null;
        }
        if (e.getSource() == telacomposicao) {
            telacomposicao = null;
        }
        if (e.getSource() == telaproduto) {
            telaproduto = null;
        }
        if (e.getSource() == telaveiculo) {
            telaveiculo = null;
        }
        if (e.getSource() == telaunidades) {
            telaunidades = null;
        }
        if (e.getSource() == pedidovenda) {
            pedidovenda = null;
        }
        if (e.getSource() == telavenda) {
            telavenda = null;
        }
        if (e.getSource() == telapedcompra) {
            telapedcompra = null;
        }
        if (e.getSource() == telacotacao) {
            telacotacao = null;
        }
        if (e.getSource() == telacontareceber) {
            telacontareceber = null;
        }
        if (e.getSource() == telarecebimnento) {
            telarecebimnento = null;
        }
        if (e.getSource() == telacontapagar) {
            telacontapagar = null;
        }
        if (e.getSource() == telapagamento) {
            telapagamento = null;
        }
        if (e.getSource() == telacaixa) {
            telacaixa = null;
        }
        if (e.getSource() == telacompra) {
            telacompra = null;
        }
        if (e.getSource() == telaordem) {
            telaordem = null;
        }
        if (e.getSource() == relclientes) {
            relclientes = null;
        }
        if (e.getSource() == relfornecedores) {
            relfornecedores = null;
        }
        if (e.getSource() == relmatprima) {
            relmatprima = null;
        }
        if (e.getSource() == relprodutos) {
            relprodutos = null;
        }
        if (e.getSource() == relcompras) {
            relcompras = null;
        }
        if (e.getSource() == relvendas) {
            relvendas = null;
        }
        if (e.getSource() == relproducao) {
            relproducao = null;
        }
        if (e.getSource() == relctapagar) {
            relctapagar = null;
        }
        if (e.getSource() == relctareceber) {
            relctareceber = null;
        }
        if (e.getSource() == relestoque) {
            relestoque = null;
        }
        if (e.getSource() == abrircaixa) {
            abrircaixa = null;
        } if (e.getSource() == telacustos) {
            telacustos = null;
        }
    }

    public void internalFrameIconified(InternalFrameEvent e) {
    }

    public void internalFrameDeiconified(InternalFrameEvent e) {
    }

    public void internalFrameActivated(InternalFrameEvent e) {
    }

    public void internalFrameDeactivated(InternalFrameEvent e) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuCadCliente;
    private javax.swing.JMenuItem jMenuCadForn;
    private javax.swing.JMenu jMenuCadProd;
    private javax.swing.JMenu jMenuCadstro;
    private javax.swing.JMenu jMenuCaixa;
    private javax.swing.JMenuItem jMenuCidade;
    private javax.swing.JMenuItem jMenuClassificacao;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenu jMenuCompras;
    private javax.swing.JMenu jMenuContPagar;
    private javax.swing.JMenu jMenuContasRec;
    private javax.swing.JMenu jMenuFornecedores;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemAbriCaixa;
    private javax.swing.JMenuItem jMenuItemCadMat;
    private javax.swing.JMenuItem jMenuItemCadProd;
    private javax.swing.JMenuItem jMenuItemComposicoes;
    private javax.swing.JMenuItem jMenuItemCotacoes;
    private javax.swing.JMenuItem jMenuItemCustos;
    private javax.swing.JMenuItem jMenuItemEstado;
    private javax.swing.JMenuItem jMenuItemFinVendas;
    private javax.swing.JMenuItem jMenuItemLancPagar;
    private javax.swing.JMenuItem jMenuItemLancRec;
    private javax.swing.JMenuItem jMenuItemLancaCompra;
    private javax.swing.JMenuItem jMenuItemMovCaixa;
    private javax.swing.JMenuItem jMenuItemOdemProd;
    private javax.swing.JMenuItem jMenuItemPag;
    private javax.swing.JMenuItem jMenuItemPedidoCompra;
    private javax.swing.JMenuItem jMenuItemRecb;
    private javax.swing.JMenuItem jMenuItemTipoMat;
    private javax.swing.JMenuItem jMenuItemUnidades;
    private javax.swing.JMenuItem jMenuItemedVendas;
    private javax.swing.JMenu jMenuLocalizacoes;
    private javax.swing.JMenu jMenuMateriaPrimaUnd;
    private javax.swing.JMenu jMenuMovimento;
    private javax.swing.JMenuItem jMenuPontuacao;
    private javax.swing.JMenu jMenuProducao;
    private javax.swing.JMenu jMenuRelario;
    private javax.swing.JMenu jMenuVendas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    public static javax.swing.JDesktopPane jdp;
    // End of variables declaration//GEN-END:variables
}
