/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaEstado.java
 *
 * Created on 09/07/2010, 22:14:23
 */
package Telacadastros;

import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import modelos.ConsultaBD;
import persistencia.Estado;
import Banco.Conexao;
import premoldados.TelaSistema;
import Telaconsulta.TelaConsulta;

/**
 *
 * @author chs
 */
public class TelaEstado extends TelaCadastro implements InternalFrameListener {

    TelaConsulta consulta;
    public Estado estadoper = new Estado();
    public ConsultaBD consultar = new ConsultaBD();
    public Vector colu = new Vector();

    /** Creates new form BeanForm */
    public TelaEstado() {
        painelCentro.setSize(340, 300);
        initComponents();

        campos.add(acaTextfieldNome);
        campos.add(acaTextfieldSigla);
        campos.add(acaTextfieldCodigo);
        habilitaCampos(false);




    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        acaLabel1 = new componentes.AcaLabel();
        acaTextfieldCodigo = new componentes.AcaTextfield();
        acaLabel2 = new componentes.AcaLabel();
        acaTextfieldNome = new componentes.AcaTextfield(true,"Nome",1);
        acaLabel3 = new componentes.AcaLabel();
        acaTextfieldSigla = new componentes.AcaTextfield(true,"Sigla",1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(800, 300));
        setSize(new java.awt.Dimension(800, 300));
        setTitle("Cadastro de Estados");

        acaLabel1.setText("Codigo");

        acaTextfieldCodigo.setEditable(false);

        acaLabel2.setText("Nome");

        acaLabel3.setText("Sigla");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getPainelCentral());
        getPainelCentral().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(acaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(acaTextfieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(acaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(acaTextfieldSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acaTextfieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(877, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acaLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1087, 1087, 1087))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaTextfieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaTextfieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaTextfieldSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void obterCampos() {
        if (tipoOperacao == ALTERANDO) {
            estadoper.setEstcod(Integer.parseInt(acaTextfieldCodigo.getText()));
        }
        estadoper.setEstnome(acaTextfieldNome.getText().toUpperCase());
        estadoper.setEstsigla(acaTextfieldSigla.getText().toUpperCase());
        if (tipoOperacao == EXCLUINDO) {
            estadoper.setEstcod(Integer.parseInt(acaTextfieldCodigo.getText()));
        }
    }

    public void preencheCampos() {
        if (tipoOperacao == PESQUISANDO) {
            campos.add(acaTextfieldCodigo);
            acaTextfieldCodigo.setText(String.valueOf(estadoper.getEstcod()));
        }
        acaTextfieldNome.setText(estadoper.getEstnome());
        acaTextfieldSigla.setText(estadoper.getEstsigla());

    }

    @Override
    protected boolean incluirBD() {
        obterCampos();
        if (estadoper.verificaDuplicidade()) {
            Conexao.executaSql(estadoper.getInsereSql());
            return true;
        }
        return false;
    }

    @Override
    protected boolean alterarBD() {
        estadoper.setEstcod(Integer.parseInt(acaTextfieldCodigo.getText()));
        obterCampos();
        if (estadoper.verificaDuplicidadeAtualizar()) {
            Conexao.executaSql(estadoper.getAtualizaSql());
            return true;
        }
        return false;

    }

    @Override
    public boolean excluirBD() {
        obterCampos();
        if ((Conexao.executaSqlExcluir(estadoper.getExcluiSql()) == Conexao.DEPENDENCIA) || (Conexao.executaSqlExcluir(estadoper.getExcluiSql()) == Conexao.OUTROERRO)) {
            JOptionPane.showMessageDialog(null, "Impossivel excluir o Estado ");
            habilitaCampos(false);
            habilitaBotoesConsulta(true);
            return false;
        } else {
            return true;
        }
    }

    @Override
    protected void consultar() {
        if (consulta == null) {
            consulta = new TelaConsulta("Consulta Estados", this, new int[]{1, 2}, new String[]{"Codigo", "Nome"}, "estado", "estcod", "estnome", null);
            colu.addElement("CODIGO");
            colu.add("NOME");
            consulta.setColu(colu);
            //consulta.setTodosB(true);
            consulta.addInternalFrameListener(this);
            tipoOperacao = PESQUISANDO;
            TelaSistema.jdp.add(consulta);
            consulta.setVisible(true);
        }
        TelaSistema.jdp.moveToFront(consulta);
        //  jXGlassBoxConsultar.setVisible(true);
        //acaComboTipo.setSelectedIndex(-1);

    }

    @Override
    protected void incluir() {
        super.incluir();
        campos.removeElement(acaTextfieldCodigo);
    }

    @Override
    protected void cancelar() {
        campos.add(acaTextfieldCodigo);
        super.cancelar();

        tipoOperacao = PADRAO;
    }

    @Override
    public void consultarDados(int codigo) {

        try {
            estadoper.setEstcod(codigo);
         //   JOptionPane.showMessageDialog(null, estadoper.getConsultaTodos());
            ResultSet rs = Conexao.executaQuery(estadoper.getConsultaTodos());
            rs.next();
            estadoper.setEstcod(rs.getInt(1));
            estadoper.setEstnome(rs.getString(2));
            estadoper.setEstsigla(rs.getString(3));
            preencheCampos();
            habilitaCampos(false);
            habilitaBotoesConsulta(true);

        } catch (Exception e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.AcaLabel acaLabel1;
    private componentes.AcaLabel acaLabel2;
    private componentes.AcaLabel acaLabel3;
    protected componentes.AcaTextfield acaTextfieldCodigo;
    private componentes.AcaTextfield acaTextfieldNome;
    private componentes.AcaTextfield acaTextfieldSigla;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void internalFrameOpened(InternalFrameEvent e) {
    }

    public void internalFrameClosing(InternalFrameEvent e) {
    }

    public void internalFrameClosed(InternalFrameEvent e) {
        if (e.getSource() == consulta) {
            consulta = null;
        }
    }

    public void internalFrameIconified(InternalFrameEvent e) {
    }

    public void internalFrameDeiconified(InternalFrameEvent e) {
    }

    public void internalFrameActivated(InternalFrameEvent e) {
    }

    public void internalFrameDeactivated(InternalFrameEvent e) {
    }

    public void mousePressed(MouseEvent e) {
    }

    public void mouseReleased(MouseEvent e) {
    }

    public void mouseEntered(MouseEvent e) {
    }

    public void mouseExited(MouseEvent e) {
    }
}
