/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaProduto.java
 *
 * Created on 30/09/2010, 22:59:10
 */
package Telacadastros;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import persistencia.Itensproduto;
import persistencia.Produto;
import Banco.Conexao;
import premoldados.TelaSistema;
import Telaconsulta.TelaConsulta;
import ajuda.PlayMovie;

/**
 *
 * @author chs
 */
public class TelaProduto extends TelaCadastro implements InternalFrameListener, KeyListener, MouseListener {

    private JTable jtTabela = new JTable() {

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    private DefaultTableModel dtm;
    public Produto prodPer = new Produto();
    public Itensproduto iteprodPer = new Itensproduto();
    TelaConsulta consulta;
    TelaMateriaPrima telamatprima;
    public Vector colu = new Vector();

    /** Creates new form BeanForm */
    public TelaProduto() {
        montaTabela(new String[]{"Codigo", "Descrição", "Quantidade", "Unitario", "Subtotal"});
        jtTabela.addMouseListener(this);
        initComponents();

        campos.add(acaTextfieldCodigo);
        campos.add(acaTextfieldCodigoIt);
        campos.add(acaTextfieldNome);
        campos.add(acaTextfieldNomeIt);
        campos.add(acaTextfieldQtde);
        campos.add(acaMonetarioTotal);
        campos.add(acaMonetarioVlrUnit);
        campos.add(acaBotoesConsulta);
        campos.add(acaBotoesAddItens);
        campos.add(acaComboComposicao);
        campos.add(acaBotoesDelIt);
        campos.add(acaBotoesConsulta);
        campos.add(acaComboStatus);
        campos.add(acaBotoesNMat);
        campos.add(acaMonetarioSubTot);
        campos.add(acaBotoesLimar);
        acaComboStatus.setSelectedIndex(1);
        acaTextfieldQtde.addKeyListener(this);
        acaMonetarioVlrUnit.addKeyListener(this);
        habilitaCampos(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelPon = new javax.swing.JPanel();
        acaLabelCodigo = new componentes.AcaLabel();
        acaTextfieldCodigo = new componentes.AcaTextfield();
        acaLabelNomeCop = new componentes.AcaLabel();
        acaTextfieldNome = new componentes.AcaTextfield(true,"Nome da composição",1);
        acaLabelRs = new componentes.AcaLabel();
        acaMonetarioTotal = new componentes.AcaMonetario(true,"Valor Total da composição",1);
        acaLabel3 = new componentes.AcaLabel();
        acaComboStatus = new componentes.AcaCombo();
        acaComboStatus.comboFiltro(new int[]{0,1,2}, new String[]{"Inativo","Ativo","Negativo"});
        jPanelItensPon1 = new javax.swing.JPanel();
        acaLabelNomeItens1 = new componentes.AcaLabel();
        acaBotoesConsulta = new componentes.AcaBotoes(false,"","Mais....");
        jScrollPaneTb = new javax.swing.JScrollPane(jtTabela);
        acaComboComposicao = new componentes.AcaCombo();
        acaComboComposicao.buscaResult("select compocod,componome  from composicao");
        acaLabel1 = new componentes.AcaLabel();
        acaLabelNome = new componentes.AcaLabel();
        acaTextfieldCodigoIt = new componentes.AcaTextfield();
        acaTextfieldNomeIt = new componentes.AcaTextfield();
        acaLabelQtd = new componentes.AcaLabel();
        acaTextfieldQtde = new componentes.AcaTextfield();
        acaLabelVlrUnit = new componentes.AcaLabel();
        acaLabel2 = new componentes.AcaLabel();
        acaMonetarioVlrUnit = new componentes.AcaMonetario();
        acaBotoesAddItens = new componentes.AcaBotoes(false,"","Adicionar Item");
        acaBotoesDelIt = new componentes.AcaBotoes(false,"","Remover item selecionado");
        acaBotoesNMat = new componentes.AcaBotoes(false,"Novo","Cadastrar materia prima");
        acaLabelSub = new componentes.AcaLabel();
        acaMonetarioSubTot = new componentes.AcaMonetario();
        acaLabelRs2 = new componentes.AcaLabel();
        acaBotoesLimar = new componentes.AcaBotoes(false,"","Limpa selecão da composicao do produto");

        setPreferredSize(new java.awt.Dimension(980, 682));
        setSize(new java.awt.Dimension(980, 682));
        setTitle("Cadastro de Produtos");

        jPanelPon.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Produto"));

        acaLabelCodigo.setText("Codigo");

        acaTextfieldCodigo.setEditable(false);

        acaLabelNomeCop.setText("Nome do Produto");

        acaLabelRs.setText("Total R$.");
        acaLabelRs.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N

        acaMonetarioTotal.setText("acaMonetario1");
        acaMonetarioTotal.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        acaLabel3.setText("Status");

        javax.swing.GroupLayout jPanelPonLayout = new javax.swing.GroupLayout(jPanelPon);
        jPanelPon.setLayout(jPanelPonLayout);
        jPanelPonLayout.setHorizontalGroup(
            jPanelPonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPonLayout.createSequentialGroup()
                        .addComponent(acaLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(acaTextfieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPonLayout.createSequentialGroup()
                        .addComponent(acaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(acaComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPonLayout.createSequentialGroup()
                        .addComponent(acaLabelNomeCop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(acaTextfieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(acaLabelRs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(acaMonetarioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanelPonLayout.setVerticalGroup(
            jPanelPonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPonLayout.createSequentialGroup()
                .addGroup(jPanelPonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acaLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaTextfieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acaLabelNomeCop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaTextfieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPonLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanelPonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(acaLabelRs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(acaMonetarioTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelItensPon1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens do Produto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        acaLabelNomeItens1.setText("Selecionar Composições");

        acaBotoesConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        acaBotoesConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesConsultaActionPerformed(evt);
            }
        });

        jScrollPaneTb.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabela Itens  do Produto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        acaComboComposicao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                acaComboComposicaoItemStateChanged(evt);
            }
        });
        acaComboComposicao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                acaComboComposicaoFocusGained(evt);
            }
        });

        acaLabel1.setText("Codigo");

        acaLabelNome.setText("Descrição");

        acaTextfieldCodigoIt.setEditable(false);

        acaTextfieldNomeIt.setEditable(false);

        acaLabelQtd.setText("Quantidade");

        acaLabelVlrUnit.setText("Valor Unitario");

        acaLabel2.setText("R$");
        acaLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        acaMonetarioVlrUnit.setEditable(false);
        acaMonetarioVlrUnit.setText("acaMonetario1");

        acaBotoesAddItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit_add1.png"))); // NOI18N
        acaBotoesAddItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesAddItensActionPerformed(evt);
            }
        });

        acaBotoesDelIt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit_remove.png"))); // NOI18N
        acaBotoesDelIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesDelItActionPerformed(evt);
            }
        });

        acaBotoesNMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesNMatActionPerformed(evt);
            }
        });

        acaLabelSub.setText("Subtotal");

        acaMonetarioSubTot.setEditable(false);
        acaMonetarioSubTot.setText("acaMonetario1");

        acaLabelRs2.setText("R$");
        acaLabelRs2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        acaBotoesLimar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/x.png"))); // NOI18N
        acaBotoesLimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesLimarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelItensPon1Layout = new javax.swing.GroupLayout(jPanelItensPon1);
        jPanelItensPon1.setLayout(jPanelItensPon1Layout);
        jPanelItensPon1Layout.setHorizontalGroup(
            jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItensPon1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItensPon1Layout.createSequentialGroup()
                        .addComponent(jScrollPaneTb, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acaBotoesDelIt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))
                    .addGroup(jPanelItensPon1Layout.createSequentialGroup()
                        .addComponent(acaLabelNomeItens1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acaComboComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acaBotoesNMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(acaBotoesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelItensPon1Layout.createSequentialGroup()
                        .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelItensPon1Layout.createSequentialGroup()
                                .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(acaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acaTextfieldCodigoIt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(acaLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acaTextfieldNomeIt, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(acaTextfieldQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(acaLabelQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(acaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acaLabelVlrUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaMonetarioVlrUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(acaLabelRs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelItensPon1Layout.createSequentialGroup()
                                .addComponent(acaLabelSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addComponent(acaMonetarioSubTot, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(acaBotoesAddItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaBotoesLimar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelItensPon1Layout.setVerticalGroup(
            jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItensPon1Layout.createSequentialGroup()
                .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItensPon1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(acaLabelNomeItens1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acaComboComposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaBotoesNMat, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(acaBotoesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItensPon1Layout.createSequentialGroup()
                        .addComponent(acaBotoesAddItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(acaBotoesLimar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelItensPon1Layout.createSequentialGroup()
                        .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItensPon1Layout.createSequentialGroup()
                                .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(acaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acaLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(acaTextfieldCodigoIt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acaTextfieldNomeIt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItensPon1Layout.createSequentialGroup()
                                .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(acaLabelVlrUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acaLabelSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acaLabelQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(acaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acaMonetarioVlrUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acaMonetarioSubTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acaTextfieldQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acaLabelRs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanelItensPon1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelItensPon1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(acaBotoesDelIt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelItensPon1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPaneTb, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelItensPon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelPon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelItensPon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getPainelCentral());
        getPainelCentral().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void acaBotoesConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesConsultaActionPerformed
        acaComboComposicao.setSelectedIndex(0);
        if (consulta == null) {
            consulta = new TelaConsulta("Consulta Composição", this, new int[]{1, 2}, new String[]{"Codigo", "Nome"}, "composicao", "compocod", "componome", null, true);
            colu.addElement("CODIGO");
            colu.add("NOME");
            consulta.setColu(colu);
            //consulta.setTodosB(true);
            consulta.addInternalFrameListener(this);
            tipoOperacao = PESQUISANDO;
            TelaSistema.jdp.add(consulta);
            consulta.setVisible(true);
        }
        TelaSistema.jdp.moveToFront(consulta);
}//GEN-LAST:event_acaBotoesConsultaActionPerformed

    private void acaComboComposicaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_acaComboComposicaoItemStateChanged

        if (acaComboComposicao.getSelectedIndex() >= 0) {
            if (acaComboComposicao.isPopupVisible()) {
                if (!validaItens(acaComboComposicao.getValor())) {
                    acaTextfieldCodigoIt.setText(String.valueOf(acaComboComposicao.getValor()));
                    acaTextfieldNomeIt.setText(acaComboComposicao.getSelectedItem().toString());

                    try {
                        ResultSet rs = Conexao.executaQuery("select compovlrtotal from composicao where compocod = " + acaComboComposicao.getValor() + "");
                        rs.next();
                        acaMonetarioVlrUnit.setValor(rs.getDouble(1));
                    } catch (SQLException e) {
                        e.printStackTrace();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Ja existe a materia prima na composição");
                    acaComboComposicao.setSelectedIndex(0);
                    return;
                }
            }

        }
}//GEN-LAST:event_acaComboComposicaoItemStateChanged

    private void acaBotoesAddItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesAddItensActionPerformed
        if (acaTextfieldQtde.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe a quantidade do Materia");

            return;
        } else {
            addItem();

            // acaMonetarioTotal.setValor(Double.parseDouble(calculaTotal(acaMonetarioVlrUnit.getValor().toString())));
            acaTextfieldCodigoIt.setText("");
            acaTextfieldNomeIt.setText("");
            acaTextfieldQtde.setText("");
            acaMonetarioSubTot.setValor(0.00);
            acaMonetarioVlrUnit.setValor(0.00);
            acaComboComposicao.setValor(0);
            calculaTotal();
        }
    }//GEN-LAST:event_acaBotoesAddItensActionPerformed

    private void acaBotoesDelItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesDelItActionPerformed
       if (tipoOperacao == ALTERANDO) {
            iteprodPer.setProdcod(Integer.parseInt(acaTextfieldCodigo.getText()));
            iteprodPer.setCompocod(Integer.parseInt(dtm.getValueAt(jtTabela.getSelectedRow(), 0).toString()));
            Conexao.executaSql(iteprodPer.getExcluiSql());
            dtm.removeRow(jtTabela.getSelectedRow());
            calculaTotal();
        } else {
            dtm.removeRow(jtTabela.getSelectedRow());
            //acaMonetarioTotal.setValor(Double.parseDouble(calculaTotal(acaMonetarioVlrUnit.getValor().toString())));
            calculaTotal();
        }
}//GEN-LAST:event_acaBotoesDelItActionPerformed

    private void acaBotoesNMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesNMatActionPerformed
        if (telamatprima == null) {
            telamatprima = new TelaMateriaPrima();
            telamatprima.addInternalFrameListener(this);
            TelaSistema.jdp.add(telamatprima);
            telamatprima.setVisible(true);
            tipoOperacao = NOVOITEM;
        }
        TelaSistema.jdp.moveToFront(telamatprima);
        tipoOperacao = NOVOITEM;
}//GEN-LAST:event_acaBotoesNMatActionPerformed

    private void acaComboComposicaoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_acaComboComposicaoFocusGained
        if (tipoOperacao == NOVOITEM) {
            acaComboComposicao.buscaResult("select compocod,componome from composicao");
        }

    }//GEN-LAST:event_acaComboComposicaoFocusGained

    private void acaBotoesLimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesLimarActionPerformed
        acaTextfieldCodigoIt.setText("");
        acaTextfieldNomeIt.setText("");
        acaMonetarioVlrUnit.setValor(0.00);
        acaTextfieldQtde.setText("");
        acaComboComposicao.setSelectedIndex(0);
        acaMonetarioSubTot.setValor(0.00);
        if (!acaMonetarioSubTot.getValor().equals("")) {
            calculaTotal();

        }
    }//GEN-LAST:event_acaBotoesLimarActionPerformed
    public void obterCampos() {
        if (tipoOperacao == ALTERANDO || tipoOperacao == EXCLUINDO) {
            prodPer.setProdcod(Integer.parseInt(acaTextfieldCodigo.getText()));
        }
        prodPer.setProdnome(acaTextfieldNome.getTexto());
        prodPer.setProdstatus(acaComboStatus.getValor());
        prodPer.setProdvalor(Double.parseDouble(acaMonetarioTotal.getValor()));

    }

    public void preencheCampos() {
        if (tipoOperacao == PESQUISANDO) {
            acaTextfieldCodigo.setText(String.valueOf(prodPer.getProdcod()));
        }
        acaTextfieldNome.setText(prodPer.getProdnome());
        acaMonetarioTotal.setValor(prodPer.getProdvalor());
        acaComboStatus.setValor(prodPer.getProdstatus());

    }

    public boolean validaItens(int codigo) {
        for (int x = 0; x < dtm.getRowCount(); x++) {
            if (Integer.parseInt((String) dtm.getValueAt(x, 0)) == codigo) {
                return true;
            }

        }
        return false;

    }

    public void montaTabela(String[] colunas) {

        dtm = (DefaultTableModel) jtTabela.getModel();
        for (int i = 0; i < colunas.length; i++) {
            dtm.addColumn(colunas[i]);
        }

        jtTabela.getColumn(jtTabela.getColumnName(0)).setPreferredWidth(50);

//        jtTabela.getColumn(jtTabela.getColumnName(2)).setPreferredWidth(90);
//        jtTabela.getColumn(jtTabela.getColumnName(3)).setPreferredWidth(90);
//        jtTabela.getColumn(jtTabela.getColumnName(4)).setPreferredWidth(90);
//        jtTabela.getColumn(jtTabela.getColumnName(5)).setPreferredWidth(100);
        jtTabela.setModel(dtm);
        TableColumnModel modeloColuna = jtTabela.getColumnModel();

        jtTabela.getTableHeader().setReorderingAllowed(false);
        jtTabela.getColumnModel().getColumn(0).setMaxWidth(80);
        jtTabela.getColumnModel().getColumn(1).setMaxWidth(190);
        jtTabela.getColumnModel().getColumn(0).setPreferredWidth(80);
        jtTabela.getColumnModel().getColumn(1).setPreferredWidth(190);
        jtTabela.getColumnModel().getColumn(2).setPreferredWidth(70);
        jtTabela.getColumnModel().getColumn(2).setMaxWidth(70);
        jtTabela.getColumnModel().getColumn(3).setPreferredWidth(100);
        jtTabela.getColumnModel().getColumn(3).setMaxWidth(100);
        jtTabela.getColumnModel().getColumn(4).setPreferredWidth(100);
        jtTabela.getColumnModel().getColumn(4).setMaxWidth(100);

        jtTabela.getColumnModel().getColumn(0).setResizable(false);


        jtTabela.getColumnModel().getColumn(1).setResizable(false);
        DefaultTableCellRenderer renderer1 = new DefaultTableCellRenderer();
        renderer1.setHorizontalAlignment(SwingConstants.CENTER);
    }

    public void montaTabela(String textoSql) {

        try {
            while (dtm.getRowCount() > 0) {
                dtm.removeRow(0);
            }
            ResultSet rs1 = Conexao.executaQuery(textoSql);
            ResultSetMetaData rsmd1 = rs1.getMetaData();
            Vector vetor;
            while (rs1.next()) {
                vetor = new Vector();
                for (int i = 0; i < rsmd1.getColumnCount(); i++) {
                    vetor.add(rs1.getString(i + 1));

                }

                dtm.addRow(vetor);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possível efetuar a pesquisa");
            e.printStackTrace();
        }

        TableColumnModel modeloColuna = jtTabela.getColumnModel();
        jtTabela.getTableHeader().setReorderingAllowed(false);
        jtTabela.getColumnModel().getColumn(0).setMaxWidth(180);
        jtTabela.getColumnModel().getColumn(0).setPreferredWidth(95);
        jtTabela.getColumnModel().getColumn(0).setResizable(false);
        jtTabela.getColumnModel().getColumn(1).setMaxWidth(70);
        jtTabela.getColumnModel().getColumn(1).setPreferredWidth(10);

        jtTabela.getColumnModel().getColumn(1).setResizable(false);

    }
  @Override
    protected void ajuda() {
        PlayMovie videos = new PlayMovie("produto.wmv");


    }
    public void addItem() {

        Object[] item = {acaTextfieldCodigoIt.getText(), acaTextfieldNomeIt.getText().toUpperCase(), acaTextfieldQtde.getText(), acaMonetarioVlrUnit.getValor(), acaMonetarioSubTot.getValor()};
        PrencheTabela(item);
        //acaTextfieldTotal.setText(String.valueOf(calculaTotal()));
    }

    public void PrencheTabela(Object[] item) {
        dtm = (DefaultTableModel) jtTabela.getModel();
        dtm.addRow(item);

        jtTabela.setModel(dtm);
    }

    public void limparPesquisa() {
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }

    @Override
    protected void cancelar() {
        super.cancelar();
        acaComboStatus.setSelectedIndex(0);
        acaComboStatus.setSelectedIndex(1);
        limparPesquisa();

    }

    @Override
    protected void incluir() {
        super.incluir();
        acaMonetarioTotal.setValor(0.00);

    }

    @Override
    protected void consultar() {
        if (consulta == null) {
            consulta = new TelaConsulta("Consulta Produto", this, new int[]{1, 2}, new String[]{"Codigo", "Nome"}, "produto", "prodcod", "prodnome", null);
            colu.addElement("CODIGO");
            colu.add("NOME");
            consulta.setColu(colu);
            //consulta.setTodosB(true);
            consulta.addInternalFrameListener(this);
            tipoOperacao = PESQUISANDO;
            TelaSistema.jdp.add(consulta);
            consulta.setVisible(true);
        }
        TelaSistema.jdp.moveToFront(consulta);
    }

    @Override
    public void consultaItens(int codigo) {
        try {
            ResultSet rs = Conexao.executaQuery("select compocod,componome,compovlrtotal from composicao where compocod = " + codigo + " ");
            rs.next();
            acaTextfieldCodigoIt.setText(String.valueOf(rs.getString(1)));
            acaTextfieldNomeIt.setText(rs.getString(2));
            acaMonetarioVlrUnit.setValor(rs.getDouble(3));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    @Override
    protected void confirmar() {
//        if (acaMonetarioTotal.getText().equals("0,00")) {
//            JOptionPane.showMessageDialog(null, "Nao Itens cadastrados");
//            return;
//        } else {
            super.confirmar();
            acaComboComposicao.setSelectedIndex(0);
            acaComboStatus.setSelectedIndex(1);
            limparPesquisa();
        
//        }
    }

    @Override
    protected void excluir() {
        super.excluir();
        acaComboComposicao.setSelectedIndex(0);
        acaComboStatus.setSelectedIndex(1);
        limparPesquisa();

    }

    public void calculaTotal() {
        acaMonetarioTotal.setValor(0.00);
        double soma = 0.00;
        double valor = 0;
        for (int x = 0; x < dtm.getRowCount(); x++) {

            if (!acaMonetarioTotal.getText().equals("")) {
                soma = soma + Double.parseDouble(jtTabela.getValueAt(x, 4).toString().replace(",", "."));
                acaMonetarioTotal.setValor(soma);
            }
        }

    }

    public void calculaUnitario() {
        int quantidade = Integer.parseInt(acaTextfieldQtde.getText());
        double valUnitario = Double.parseDouble(acaMonetarioVlrUnit.getValor());
        double valTotal = ((int) ((quantidade * valUnitario) * 100.0)) / 100.0;
        acaMonetarioSubTot.setValor(valTotal);
    }

    @Override
    protected boolean incluirBD() {
        obterCampos();
        if (prodPer.verificaDuplicidade()) {
            ResultSet rs = null;
            try {
                rs = prodPer.getInsereRs();
                rs.next();
                iteprodPer.setProdcod(rs.getInt(1));
                for (int x = 0; x < jtTabela.getRowCount(); x++) {

                    iteprodPer.setCompocod(Integer.parseInt(jtTabela.getValueAt(x, 0).toString()));
                    iteprodPer.setItenqtdeprod(Float.parseFloat(jtTabela.getValueAt(x, 2).toString()));
                    iteprodPer.setItenvalorunit(Double.parseDouble(jtTabela.getValueAt(x, 4).toString()));
                     iteprodPer.setItevlrUnita(Double.parseDouble(jtTabela.getValueAt(x, 3).toString()));

                    Conexao.executaSql(iteprodPer.getInsereSql());
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
            return true;
        }
        return false;
    }

    @Override
    public void consultarDados(int codigo) {
        try {
            prodPer.setProdcod(codigo);

            ResultSet rs = Conexao.executaQuery(prodPer.getConsultaTodos());
            rs.next();
            prodPer.setProdcod(rs.getInt(1));
            iteprodPer.setProdcod(rs.getInt(1));
            prodPer.setProdnome(rs.getString(2));
            prodPer.setProdvalor(rs.getDouble(3));
            prodPer.setProdstatus(rs.getInt(4));




        } catch (SQLException e) {
            e.printStackTrace();
        }
        preencheCampos();
        montaTabela(iteprodPer.getConsultaSqlString());
        habilitaCampos(false);
        habilitaBotoesConsulta(true);

    }

    @Override
    protected boolean alterarBD() {
        obterCampos();
        if (prodPer.verificaDuplicidadeAtualiza()) {
            ResultSet rs = null;
            try {
                Conexao.executaSql(prodPer.getAtualizaSql());

                iteprodPer.setProdcod(Integer.parseInt(acaTextfieldCodigo.getText()));

                for (int x = 0; x < dtm.getRowCount(); x++) {
                    iteprodPer.setCompocod(Integer.parseInt(jtTabela.getValueAt(x, 0).toString()));
                    iteprodPer.setItenqtdeprod(Float.parseFloat(jtTabela.getValueAt(x, 2).toString()));
                    iteprodPer.setItenvalorunit(Double.parseDouble(jtTabela.getValueAt(x, 4).toString()));
                       iteprodPer.setItevlrUnita(Double.parseDouble(jtTabela.getValueAt(x, 3).toString()));
                    Conexao.executaSql(iteprodPer.getAtualizaSql());
                }
                limparPesquisa();
            } catch (Exception e) {
            }
            return true;

        }
        return false;
    }

    @Override
    protected boolean excluirBD() {
        prodPer.setProdcod(Integer.parseInt(acaTextfieldCodigo.getText()));
        int opcao = -1;
        if (Conexao.executaSqlExcluir(prodPer.getExcluiSql()) == Conexao.DEPENDENCIA) {
            opcao = 1;
        } else {
            opcao = 0;
        }
        if (Conexao.executaSqlExcluir(prodPer.getExcluiSql()) == Conexao.OUTROERRO) {
            opcao = 0;
            return false;
        }
        if (opcao == 1) {
            Object[] botoes = {"Sim", "Não"};
            int mensagem = JOptionPane.showOptionDialog(null, "Existe dependencia de dados \n Deseja inativar o cadastro",
                    "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[0]);
            if (mensagem == JOptionPane.YES_OPTION) {

                Conexao.executaSql("execute procedure inativastatus(" + prodPer.getProdcod() + ",'produto','prodcod','prodstatus') ");
                habilitarBotoes(true);
                habilitaCampos(false);
                return false;

            }
            if (mensagem == JOptionPane.NO_OPTION) {
                habilitaCampos(true);
                return false;
            }


        }
        return true;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.AcaBotoes acaBotoesAddItens;
    private componentes.AcaBotoes acaBotoesConsulta;
    private componentes.AcaBotoes acaBotoesDelIt;
    private componentes.AcaBotoes acaBotoesLimar;
    private componentes.AcaBotoes acaBotoesNMat;
    private componentes.AcaCombo acaComboComposicao;
    private componentes.AcaCombo acaComboStatus;
    private componentes.AcaLabel acaLabel1;
    private componentes.AcaLabel acaLabel2;
    private componentes.AcaLabel acaLabel3;
    private componentes.AcaLabel acaLabelCodigo;
    private componentes.AcaLabel acaLabelNome;
    private componentes.AcaLabel acaLabelNomeCop;
    private componentes.AcaLabel acaLabelNomeItens1;
    private componentes.AcaLabel acaLabelQtd;
    private componentes.AcaLabel acaLabelRs;
    private componentes.AcaLabel acaLabelRs2;
    private componentes.AcaLabel acaLabelSub;
    private componentes.AcaLabel acaLabelVlrUnit;
    private componentes.AcaMonetario acaMonetarioSubTot;
    private componentes.AcaMonetario acaMonetarioTotal;
    private componentes.AcaMonetario acaMonetarioVlrUnit;
    private componentes.AcaTextfield acaTextfieldCodigo;
    private componentes.AcaTextfield acaTextfieldCodigoIt;
    private componentes.AcaTextfield acaTextfieldNome;
    private componentes.AcaTextfield acaTextfieldNomeIt;
    private componentes.AcaTextfield acaTextfieldQtde;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelItensPon1;
    private javax.swing.JPanel jPanelPon;
    private javax.swing.JScrollPane jScrollPaneTb;
    // End of variables declaration//GEN-END:variables

    public void internalFrameOpened(InternalFrameEvent e) {
    }

    public void internalFrameClosing(InternalFrameEvent e) {
    }

    public void internalFrameClosed(InternalFrameEvent e) {
        if (e.getSource() == consulta) {
            consulta = null;
        }
    }

    public void internalFrameIconified(InternalFrameEvent e) {
    }

    public void internalFrameDeiconified(InternalFrameEvent e) {
    }

    public void internalFrameActivated(InternalFrameEvent e) {
    }

    public void internalFrameDeactivated(InternalFrameEvent e) {
    }

    public void keyTyped(KeyEvent e) {
    }

    public void keyPressed(KeyEvent e) {
    }

    public void keyReleased(KeyEvent e) {
        calculaUnitario();
    }

    public void mouseClicked(MouseEvent e) {
        if (e.getClickCount() == 2) {
            acaTextfieldCodigoIt.setText((String) dtm.getValueAt(jtTabela.getSelectedRow(), 0));
            acaTextfieldNomeIt.setText((String) dtm.getValueAt(jtTabela.getSelectedRow(), 1));
            acaTextfieldQtde.setText((String) dtm.getValueAt(jtTabela.getSelectedRow(), 2));
            System.out.println(dtm.getValueAt(jtTabela.getSelectedRow(), 3));
            System.out.println(dtm.getValueAt(jtTabela.getSelectedRow(), 4));
            acaMonetarioVlrUnit.setValor((Double.parseDouble(dtm.getValueAt(jtTabela.getSelectedRow(), 3).toString().replace(",", "."))));
            acaMonetarioSubTot.setValor(Double.parseDouble(dtm.getValueAt(jtTabela.getSelectedRow(), 4).toString().replace(",", ".")));
//            String teste = dtm.getValueAt(jtTabela.getSelectedRow(), 4).toString().replace(",", "");
//            acaMonetarioSubTot.setValor(Double.parseDouble(teste));
            dtm.removeRow(jtTabela.getSelectedRow());

            calculaTotal();
            //acaMonetarioTotal.setValor(Double.parseDouble(calculaTotal(acaMonetarioVlrUnit.getValor().toString())));
        }
    }

    public void mousePressed(MouseEvent e) {
    }

    public void mouseReleased(MouseEvent e) {
    }

    public void mouseEntered(MouseEvent e) {
    }

    public void mouseExited(MouseEvent e) {
    }
}
