/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AbriCaixa.java
 *
 * Created on 07/10/2011, 20:43:04
 */
package telaMovimenacao;

import Banco.Conexao;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import persistencia.Caixa;
import persistencia.Movcaixa;

/**
 *
 * @author cristiano
 */
public class AbriCaixa extends javax.swing.JInternalFrame implements InternalFrameListener {

    Caixa caixaPer = new Caixa();
    Movcaixa movcxPer = new Movcaixa();
    FecharCaixa fecharcaixa;
    protected final int ABRINDO = 1;
    protected final int FECHANDO = 0;
    protected final int RETIRADA = 1;
    protected final int PADRAO = -1;
    protected int tipooperacao = PADRAO;
    protected int tipoabertura = PADRAO;

    /** Creates new form AbriCaixa */
    public AbriCaixa() {

        initComponents();
        acaDataChooserCx.setDate(new Date());
        jButton1.setEnabled(false);
        verSituacao();
        posicaoTela();


    }

    public void obtemCampos() {
        caixaPer.setCxdata(acaDataChooserCx.getValor());
        if (acaMonetarioSaldoIni.getValor().equals("")) {
            caixaPer.setCxsaldoini(0);
            movcxPer.setMovdata(acaDataChooserCx.getValor());
            movcxPer.setMovdescr("retirada do caixa");
            movcxPer.setMovstatus(2);
            movcxPer.setMovtipo(2);
            //movcxPer.setMovvlr(Double.parseDouble(acaMonetarioSaldoIni.getValor()));

        } else {
            caixaPer.setCxsaldoini(Double.parseDouble(acaMonetarioSaldoIni.getValor()));
        }
        caixaPer.setCxstatus(1);


    }

    public void abrir() {

        if (tipooperacao == ABRINDO) {
            obtemCampos();
            Conexao.executaSql(caixaPer.getInsereSql());
            if (acaMonetarioSaldoIni.getValor().equals("")) {
                Conexao.executaSql(movcxPer.getInsereSql());
            }
            JOptionPane.showMessageDialog(null, "Caixa Aberto com sucesso");
            dispose();
        }
        if (tipooperacao == FECHANDO) {
            Conexao.executaSql("update caixa set cxstatus = 2 where cxcod = " + caixaPer.getCxcod() + "");
            JOptionPane.showMessageDialog(null, "Caixa Fechado com sucesso");
            dispose();
        }



    }

    public boolean verSituacao() {
        ResultSet rs = null;
        rs = Conexao.executaQuery("select  CAIXA.CXSTATUS, caixa.cxsaldotot , CAIXA.CXSALDOINI, caixa.cxcod from caixa where CAIXA.CXCOD = (select max(CAIXA.CXCOD)from caixa)");
        try {
            rs.next();

            if (rs.getInt(1) == 1) {
                JOptionPane.showMessageDialog(null, "Caixa esta Aberto");
                jButton1.setText("Fechar Caixa");
                jButton1.setEnabled(true);
                tipooperacao = FECHANDO;
                this.setTitle("Fechar Caixa");
                acaLabelSaldoIniFin.setText("Total");
                jCheckBox1.setVisible(false);
                acaMonetarioSaldoIni.setValor(rs.getDouble(2));
                acaLabelSaldo.setText(rs.getString(2));
                caixaPer.setCxcod(rs.getInt(4));

                return true;

            } else {
                if (rs.getDouble(2) == 0) {
                    acaMonetarioSaldoIni.setEditable(true);
                } else {
                    acaMonetarioSaldoIni.setEditable(false);
                }
                acaLabelSaldo.setText(rs.getString(2));
                jButton1.setEnabled(true);
                jButton1.setText("Abrir Caixa");
                this.setTitle("Abrir Caixa");
                acaLabelSaldoIniFin.setText("Inicial");

                movcxPer.setCxcod(rs.getInt(4));
                movcxPer.setMovvlr(rs.getDouble(2));
                tipooperacao = ABRINDO;
                return false;

            }
        } catch (SQLException ex) {
            Logger.getLogger(AbriCaixa.class.getName()).log(Level.SEVERE, null, ex);
        }

        return false;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        acaLabel1 = new componentes.AcaLabel();
        acaMonetarioSaldoIni = new componentes.AcaMonetario();
        acaLabel2 = new componentes.AcaLabel();
        acaLabelSaldo = new componentes.AcaLabel();
        acaDataChooserCx = new componentes.acaDataChooser();
        acaLabel3 = new componentes.AcaLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        acaLabelSaldoIniFin = new componentes.AcaLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        acaLabel1.setText("Saldo ");

        acaMonetarioSaldoIni.setText("acaMonetario1");

        acaLabel2.setText("SALDO : ");

        acaLabelSaldo.setText("acaLabel3");

        acaDataChooserCx.setEnabled(false);

        acaLabel3.setText("Data");

        jCheckBox1.setText("Importar Saldo Anterior");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        acaLabelSaldoIniFin.setText("acaLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(acaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acaLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(acaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acaDataChooserCx, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(acaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(acaLabelSaldoIniFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acaMonetarioSaldoIni, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCheckBox1))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(acaLabelSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(acaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(acaDataChooserCx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaMonetarioSaldoIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaLabelSaldoIniFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        abrir();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            acaMonetarioSaldoIni.setValor(Double.parseDouble(acaLabelSaldo.getText()));
        } else {
            tipoabertura = RETIRADA;
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.acaDataChooser acaDataChooserCx;
    private componentes.AcaLabel acaLabel1;
    private componentes.AcaLabel acaLabel2;
    private componentes.AcaLabel acaLabel3;
    private componentes.AcaLabel acaLabelSaldo;
    private componentes.AcaLabel acaLabelSaldoIniFin;
    private componentes.AcaMonetario acaMonetarioSaldoIni;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void internalFrameOpened(InternalFrameEvent e) {
    }

    public void internalFrameClosing(InternalFrameEvent e) {
    }

    public void internalFrameClosed(InternalFrameEvent e) {
        if (e.getSource() == fecharcaixa) {
            fecharcaixa = null;

        }
    }

    public void internalFrameIconified(InternalFrameEvent e) {
    }

    public void internalFrameDeiconified(InternalFrameEvent e) {
    }

    public void internalFrameActivated(InternalFrameEvent e) {
    }

    public void internalFrameDeactivated(InternalFrameEvent e) {
    }

    public void posicaoTela() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 200);
    }
}
