/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaCotacao1.java
 *
 * Created on 19/04/2011, 20:57:50
 */
package telaMovimenacao;

import IntefaceAca.AcaComponente;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import persistencia.Cotacoes;
import persistencia.Cotfornecedor;
import persistencia.Itenscotprod;
import Banco.Conexao;
import premoldados.TelaSistema;
import Telacadastros.TelaFornecedor;
import Telacadastros.TelaMateriaPrima;
import Telaconsulta.TelaConsMov;
import componentes.AcaTabela;

/**
 *
 * @author cristiano
 */
public class TelaCotacao extends javax.swing.JInternalFrame implements InternalFrameListener, MouseListener {

    public AcaTabela jTabela = new AcaTabela();
    public AcaTabela jTabelaConsulta = new AcaTabela();
    public AcaTabela jTabelaFor = new AcaTabela();
    TelaConsultaPed consultaPed;
    ConsultaCotacao consultacotacao;
    TelaMateriaPrima telamateria;
    TelaConsMov telaconsultamat;
    TelaConsMov telaconsultafor;
    TelaFornecedor telafornecedor;
    public Vector colu = new Vector();
    Cotacoes cotacoePer = new Cotacoes();
    Cotfornecedor cotforPer = new Cotfornecedor();
    Itenscotprod itenscotaper = new Itenscotprod();
    protected final int PADRAO = 0;
    protected final int PESQUISANDO = 1;
    protected final int INCLUINDO = 2;
    protected final int ALTERANDO = 3;
    protected final int EXCLUINDO = 4;
    protected final int NOVOPESSOA = 8;
    protected final int NOVOITEM = 5;
    public final int FECHADO = 2;
    protected final int ABERTO = 1;
    public final int CANCELADO = 0;
    protected final int AUTOMATICO = 3;
    protected int tipoOperacao = PADRAO;
    public Vector<AcaComponente> camposPainel1 = new Vector();
    public Vector<AcaComponente> camposPainel2 = new Vector();
    public Vector<AcaComponente> camposPainel3 = new Vector();

    /** Creates new form TelaCotacao1 */
    public TelaCotacao() {
        initComponents();
        camposPainel1.add(acaTextfieldCodigo);
        camposPainel1.add(acaDataFin);
        camposPainel1.add(acaDataIni);
        camposPainel1.add(acaComboStatus);
        camposPainel1.add(acaComboTipoItens);
        camposPainel2.add(acaComboProd);
        camposPainel2.add(acaTextfieldCodItens);
        camposPainel2.add(acaTextfieldQtde);
        camposPainel2.add(acaMonetarioSubtot);
        camposPainel2.add(acaMonetarioUnit);
        camposPainel2.add(acaTextfieldDes);
        camposPainel2.add(acaBotoesAddItes);
        camposPainel2.add(acaBotoesDelItens);
        camposPainel2.add(acaBotoesDelSelIten);
        camposPainel2.add(acaBotoesNovoProd);
        camposPainel2.add(acaBotoesConProd);
        camposPainel3.add(acaTextfieldCodFor);
        camposPainel3.add(acaComboFor);
        camposPainel3.add(acaBotoesAddfor);
        camposPainel3.add(acaBotoesConsulFor);
        camposPainel3.add(acaBotoesDelFor);
        jTabela.montaTabela(new String[]{"Codigo", "Descrição", "Quantidade", "Valor Unitario", "Subtotal"}, new int[]{70, 200, 100, 100, 100});
        jTabelaFor.montaTabela(new String[]{"Codigo", "Nome"}, new int[]{70, 300});
        acaComboStatus.comboFiltro(new int[]{ABERTO, FECHADO, CANCELADO, AUTOMATICO}, new String[]{"Aberta", "Encerrada", "Cancelada", "Automatica"});
        habilitaCampos(false, camposPainel1);
        habilitaCampos(false, camposPainel2);
        habilitaCampos(false, camposPainel3);
        posicaoTela();


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        acaLabel1 = new componentes.AcaLabel();
        acaTextfieldCodigo = new componentes.AcaTextfield();
        acaLabel2 = new componentes.AcaLabel();
        acaDataIni = new componentes.AcaData();
        acaLabel3 = new componentes.AcaLabel();
        acaDataFin = new componentes.AcaData();
        acaLabel4 = new componentes.AcaLabel();
        acaComboStatus = new componentes.AcaCombo();
        acaLabel5 = new componentes.AcaLabel();
        acaComboTipoItens = new componentes.AcaCombo();
        acaComboTipoItens.buscaResult("select tipomatcod, tipomatfor from tipomateria");
        jScrollPaneConsulta = new javax.swing.JScrollPane(jTabelaConsulta);
        jPanel2 = new javax.swing.JPanel();
        acaLabelSel = new componentes.AcaLabel();
        acaComboProd = new componentes.AcaCombo(false, "");
        acaBotoesConProd = new componentes.AcaBotoes(false, "", "+ Registros");
        acaBotoesNovoProd = new componentes.AcaBotoes(false,"","Novo Produto");
        acaLabel6 = new componentes.AcaLabel();
        acaLabel7 = new componentes.AcaLabel();
        acaLabel8 = new componentes.AcaLabel();
        acaTextfieldCodItens = new componentes.AcaTextfield(false,"codigo itens",1);
        acaTextfieldDes = new componentes.AcaTextfield(false,"descricao itens",1);
        acaTextfieldQtde = new componentes.AcaTextfield(false, "quantidade", 1);
        acaBotoesAddItes = new componentes.AcaBotoes(false,"","");
        acaBotoesDelItens = new componentes.AcaBotoes(false,null,null);
        jScrollPane2 = new javax.swing.JScrollPane(jTabela);
        acaBotoesDelSelIten = new componentes.AcaBotoes(false,"","Apagar item selecionado");
        acaMonetarioUnit = new componentes.AcaMonetario(false,"Valor unitario",1);
        acaLabel9 = new componentes.AcaLabel();
        acaLabel10 = new componentes.AcaLabel();
        acaMonetarioSubtot = new componentes.AcaMonetario(false,"subtotal",1);
        jPanel3 = new javax.swing.JPanel();
        acaLabel11 = new componentes.AcaLabel();
        acaLabel12 = new componentes.AcaLabel();
        acaTextfieldCodFor = new componentes.AcaTextfield();
        acaComboFor = new componentes.AcaCombo();
        acaBotoesConsulFor = new componentes.AcaBotoes();
        acaBotoesAddfor = new componentes.AcaBotoes();
        jScrollPaneFor = new javax.swing.JScrollPane(jTabelaFor);
        acaBotoesDelFor = new componentes.AcaBotoes();
        acaBotoesConsultar = new componentes.AcaBotoes();
        acaBotoesIncuir = new componentes.AcaBotoes();
        acaBotoesExcluir = new componentes.AcaBotoes();
        acaBotoesConfirmar = new componentes.AcaBotoes();
        acaBotoesCancelar = new componentes.AcaBotoes();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cotação ");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        acaLabel1.setText("Codigo");

        acaTextfieldCodigo.setEditable(false);

        acaLabel2.setText("Data Inicial");

        acaLabel3.setText("Data Final");

        acaLabel4.setText("Status");

        acaLabel5.setText("Tipo de Itens ");

        acaComboTipoItens.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                acaComboTipoItensItemStateChanged(evt);
            }
        });
        acaComboTipoItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaComboTipoItensActionPerformed(evt);
            }
        });

        jScrollPaneConsulta.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPaneConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaTextfieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaDataFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acaLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acaComboTipoItens, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(acaLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(99, 99, 99))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(acaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acaTextfieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(acaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acaDataIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(acaLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(acaDataFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(acaLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acaComboTipoItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(acaLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(acaComboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pedido de Cotação", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setEnabled(false);

        acaLabelSel.setText("Material");

        acaComboProd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                acaComboProdItemStateChanged(evt);
            }
        });

        acaBotoesConProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        acaBotoesConProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesConProdActionPerformed(evt);
            }
        });

        acaBotoesNovoProd.setText("Novo");

        acaLabel6.setText("Codigo");

        acaLabel7.setText("Descrição");

        acaLabel8.setText("Quantidade");

        acaTextfieldCodItens.setEditable(false);
        acaTextfieldCodItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaTextfieldCodItensActionPerformed(evt);
            }
        });

        acaTextfieldDes.setEditable(false);

        acaBotoesAddItes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit_add1.png"))); // NOI18N
        acaBotoesAddItes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesAddItesActionPerformed(evt);
            }
        });

        acaBotoesDelItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/x.png"))); // NOI18N
        acaBotoesDelItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesDelItensActionPerformed(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela de Itens do Pedido"));

        acaBotoesDelSelIten.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/edit_remove.png"))); // NOI18N
        acaBotoesDelSelIten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesDelSelItenActionPerformed(evt);
            }
        });

        acaMonetarioUnit.setText("acaMonetario1");

        acaLabel9.setText("Valor Unitario");

        acaLabel10.setText("Subtotal");

        acaMonetarioSubtot.setText("acaMonetario2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acaLabelSel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(acaComboProd, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(acaBotoesConProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(acaBotoesNovoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acaBotoesDelSelIten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(acaLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(acaLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(acaLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(acaTextfieldQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(acaMonetarioUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(acaMonetarioSubtot, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(acaBotoesAddItes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(acaBotoesDelItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(acaLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(acaLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(acaTextfieldCodItens, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acaTextfieldDes, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(acaLabelSel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(acaComboProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(acaBotoesConProd, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaBotoesNovoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acaLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acaTextfieldCodItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaTextfieldDes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acaLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acaTextfieldQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaMonetarioUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaMonetarioSubtot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaBotoesAddItes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaBotoesDelItens, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(acaBotoesDelSelIten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Itens da Cotação", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        acaLabel11.setText("Codigo");

        acaLabel12.setText("Nome");

        acaTextfieldCodFor.setEditable(false);

        acaComboFor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                acaComboForItemStateChanged(evt);
            }
        });

        acaBotoesConsulFor.setText("+ Fornecedores");
        acaBotoesConsulFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesConsulForActionPerformed(evt);
            }
        });

        acaBotoesAddfor.setText("Adcionar");
        acaBotoesAddfor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesAddforActionPerformed(evt);
            }
        });

        acaBotoesDelFor.setText("Remover");
        acaBotoesDelFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesDelForActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(acaLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acaTextfieldCodFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(acaComboFor, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(acaBotoesAddfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(acaBotoesConsulFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(acaLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPaneFor, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acaBotoesDelFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addGap(113, 113, 113))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acaLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acaTextfieldCodFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaComboFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaBotoesAddfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaBotoesConsulFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPaneFor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(acaBotoesDelFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fornecedores", jPanel3);

        acaBotoesConsultar.setText("Consultar");
        acaBotoesConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesConsultarActionPerformed(evt);
            }
        });

        acaBotoesIncuir.setText("Incluir");
        acaBotoesIncuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesIncuirActionPerformed(evt);
            }
        });

        acaBotoesExcluir.setText("Excluir");
        acaBotoesExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesExcluirActionPerformed(evt);
            }
        });

        acaBotoesConfirmar.setText("Confirmar");
        acaBotoesConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesConfirmarActionPerformed(evt);
            }
        });

        acaBotoesCancelar.setText("Cancelar");
        acaBotoesCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acaBotoesCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(acaBotoesConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaBotoesExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaBotoesConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaBotoesIncuir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acaBotoesCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(acaBotoesConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acaBotoesIncuir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acaBotoesExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acaBotoesConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acaBotoesCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void obterCampos() {
        if (tipoOperacao == ALTERANDO || tipoOperacao == EXCLUINDO) {
            cotacoePer.setCotcod(acaTextfieldCodigo.getInteiro);
        }
        cotacoePer.setCotdata(acaDataIni.getValor());
        cotacoePer.setCotdatafin(acaDataFin.getValor());
        cotacoePer.setCotstatus(acaComboStatus.getValor());
        cotacoePer.setTipomatcod(acaComboTipoItens.getValor());
    }

    public void preencheCampos() {
    }

    protected void habilitaCampos(boolean status, Vector<AcaComponente> vetor) {

        for (int i = 0; i < vetor.size(); i++) {

            vetor.get(i).habilitar(status);
        }


    }

    public void habilitarBotoes(boolean status) {
        acaBotoesIncuir.setEnabled(!status);
        acaBotoesConsultar.setEnabled(!status);
//        acaBotoesAlterar.setEnabled(status);
        acaBotoesCancelar.setEnabled(status);
        acaBotoesConfirmar.setEnabled(status);
        acaBotoesExcluir.setEnabled(status);
    }

    public void habilitarBotoesConsulta(boolean status) {
        acaBotoesIncuir.setEnabled(!status);
        acaBotoesConsultar.setEnabled(!status);

        acaBotoesCancelar.setEnabled(status);
        acaBotoesConfirmar.setEnabled(status);
        acaBotoesExcluir.setEnabled(status);
    }

    protected void confirmar() {

        if (!validarCampos(camposPainel1)) {
            return;
        }
        if (!validarCampos(camposPainel2)) {
            return;
        }
        if (!validarCampos(camposPainel3)) {
            return;
        }
        if ((tipoOperacao == INCLUINDO) && !incluindoBD()) {
            return;
        } else if ((tipoOperacao == ALTERANDO) && !alterandoBD()) {
            return;
        } else if ((tipoOperacao == EXCLUINDO) && !excluindoBD()) {
            camposPainel1.removeAllElements();
            camposPainel2.removeAllElements();
            camposPainel3.removeAllElements();
            return;
        }
        if (tipoOperacao == INCLUINDO) {
            JOptionPane.showMessageDialog(null, "DADOS GRAVADOS COM SUCESSO");
        }
        if (tipoOperacao == ALTERANDO) {
            JOptionPane.showMessageDialog(null, "DADOS ALTERADOS COM SUCESSO");
        }
        tipoOperacao = PADRAO;
        limparCampos(camposPainel1);
        limparCampos(camposPainel2);
        limparCampos(camposPainel3);
        habilitarBotoes(false);
        habilitaCampos(false, camposPainel1);
        habilitaCampos(false, camposPainel2);
        habilitaCampos(false, camposPainel3);
        ;
    }

    protected boolean validarCampos(Vector<AcaComponente> campos) {
        String errosObrigatorios = "";
        String errosValidacao = "";
        String mensagemErro = "";
        for (int contador = 0; contador < campos.size(); contador++) {
            if ((campos.get(contador).eObrigatorio()) && (campos.get(contador).eVazio())) {
                errosObrigatorios = errosObrigatorios + campos.get(contador).getDica() + "\n";
            }
            if ((!campos.get(contador).eVazio()) && (!campos.get(contador).eValido())) {
                errosValidacao = errosValidacao + campos.get(contador).getDica() + "\n";
            }
        }
        if (!errosObrigatorios.isEmpty()) {
            mensagemErro = "Campos obrigatorios não preenchidos: \n" + errosObrigatorios;
        }
        if (!errosValidacao.isEmpty()) {
            mensagemErro = mensagemErro + "\n\nCampos Invalidos: \n" + errosValidacao;
        }
        if (!mensagemErro.isEmpty()) {
            JOptionPane.showMessageDialog(null, mensagemErro);
            return false;
        } else {
            return true;
        }

    }

    protected void limparCampos(Vector<AcaComponente> campos) {
        for (int i = 0; i < campos.size(); i++) {
            campos.get(i).limpar();

        }

    }

    public void addItemTabelaFor(Object[] itemConsulta, int codigo) {

        if (!jTabelaFor.validaItens(codigo)) {
            jTabelaFor.PrencheTabela(itemConsulta);
        } else {
            JOptionPane.showMessageDialog(null, "ja existe o fornecedor na listagem abaixo");
            return;
        }
    }

    public boolean incluindoBD() {
        obterCampos();
        ResultSet rs = cotacoePer.getInsereRs();
        try {
            rs.next();
            itenscotaper.setCotcod(rs.getInt(1));
            cotforPer.setCotcod(rs.getInt(1));
         //   System.out.println("chegou");
            for (int y = 0; y < jTabelaFor.getRowCount(); y++) {
                for (int x = 0; x < jTabela.getRowCount(); x++) {
                    itenscotaper.setMatcod(Integer.parseInt(jTabela.getValueAt(x, 0).toString()));
                    itenscotaper.setItendcotqtde(Float.parseFloat(jTabela.getValueAt(x, 2).toString()));
                    if (jTabela.dtm.getValueAt(x, 3).equals("0,00")) {
                        itenscotaper.setItenscotunt(0.00);
                    } else {
                        itenscotaper.setItenscotunt(Float.parseFloat(jTabela.getValueAt(x, 3).toString().replace(",", ".")));
                    }
                    if (jTabela.dtm.getValueAt(x, 4).equals("0,00")) {
                        itenscotaper.setItenscotsubtotal(0.00);
                    } else {
                        itenscotaper.setItenscotsubtotal(Float.parseFloat(jTabela.getValueAt(x, 4).toString().replace(",", ".")));
                    }
                    itenscotaper.setForcod(Integer.parseInt(jTabelaFor.getValueAt(y, 0).toString()));
                    Conexao.executaSql(itenscotaper.getInsereSql());

                }
                cotforPer.setForcod(Integer.parseInt(jTabelaFor.getValueAt(y, 0).toString()));
                cotforPer.setFonome(String.valueOf(jTabelaFor.getValueAt(y, 1)));
                cotforPer.setCodstatus(acaComboStatus.getValor());
                Conexao.executaSql(cotforPer.getInsereSql());
            }
//            for (int y = 0; y < jTabelaFor.getRowCount(); y++) {
//                cotforPer.setForcod(Integer.parseInt(jTabelaFor.getValueAt(y, 0).toString()));
//                cotforPer.setFonome(String.valueOf(jTabelaFor.getValueAt(y, 1)));
//                cotforPer.setCodstatus(acaComboStatus.getValor());
//                Conexao.executaSql(cotforPer.getInsereSql());
//
//            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        jTabela.limparPesquisa();
        jTabelaFor.limparPesquisa();
        return true;
    }

    public void consultar() {
        if (jTabelaConsulta.getColumnCount() > 0) {
            jTabelaConsulta.montaTabela("SELECT distinct C2.COTCOD, C2.FORCOD,C2.FONOME,C1.COTDATA,T1.TIPOMATFOR "
                    + "FROM COTFORNECEDOR C2,COTACOES C1,TIPOMATERIA T1 "
                    + "WHERE T1.TIPOMATCOD = C1.TIPOMATCOD AND  C1.COTCOD = C2.COTCOD and c2.codstatus != " + FECHADO + " and c2.codstatus != " + CANCELADO + "");
        } else {
            if (tipoOperacao != PESQUISANDO) {
                jScrollPaneConsulta.setEnabled(true);
                jTabelaConsulta.montaTabela(new String[]{"Cod. Cotação", "Cod. Fornecedor", "Nome", "Data Inicial", "Tipo de Material"}, new int[]{70, 70, 200, 100, 150});
                jTabelaConsulta.montaTabela("SELECT distinct C2.COTCOD, C2.FORCOD,C2.FONOME,C1.COTDATA,T1.TIPOMATFOR "
                        + "FROM COTFORNECEDOR C2,COTACOES C1,TIPOMATERIA T1 "
                        + "WHERE T1.TIPOMATCOD = C1.TIPOMATCOD AND  C1.COTCOD = C2.COTCOD and c2.codstatus != " + FECHADO + " and c2.codstatus != " + CANCELADO + "");
                tipoOperacao = PESQUISANDO;
                jTabelaConsulta.addMouseListener(this);
                habilitarBotoesConsulta(true);
            } else {
                return;
            }
        }
    }

    public boolean alterandoBD() {
        return false;
    }

    public boolean excluindoBD() {
        return false;
    }
    private void acaComboProdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_acaComboProdItemStateChanged
        if (acaComboProd.getSelectedIndex() >= 0) {
            if (acaComboProd.isPopupVisible()) {
                if (!jTabela.validaItens(acaComboProd.getValor())) {
                    acaTextfieldCodItens.setText(String.valueOf(acaComboProd.getValor()));
                    acaTextfieldDes.setText(acaComboProd.getSelectedItem().toString());
                    acaTextfieldQtde.requestFocus();
                    habilitaCampos(true, camposPainel3);
                    //                    try {
                    //                        ResultSet rs = Conexao.executaQuery("select matvalor from materiaprima where matcod = " + acaComboProd.getValor() + "");
                    //                        rs.next();
                    ////                        acaMonetarioUnit.setValor(rs.getDouble(1));
                    //                    } catch (SQLException e) {
                    //                        e.printStackTrace();
                    //                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Ja existe  o material ");
                    acaComboProd.setSelectedIndex(0);
                    return;
                }
            }

        }
}//GEN-LAST:event_acaComboProdItemStateChanged

    private void acaBotoesConProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesConProdActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_acaBotoesConProdActionPerformed

    private void acaTextfieldCodItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaTextfieldCodItensActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_acaTextfieldCodItensActionPerformed

    private void acaBotoesAddItesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesAddItesActionPerformed
        if (acaTextfieldQtde.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe a quantidade do Materia");

            return;
        } else {
            addItem(jTabela);

            // acaMonetarioTotal.setValor(Double.parseDouble(calculaTotal(acaMonetarioVlrUnit.getValor().toString())));
            acaTextfieldCodItens.setText("");
            acaTextfieldDes.setText("");
            acaTextfieldQtde.setText("");
            acaMonetarioUnit.setValor(0.00);
            acaMonetarioSubtot.setValor(0.00);

            acaComboProd.setValor(0);
            if (tipoOperacao == ALTERANDO) {
                // calculaTotal();
            }

        }
}//GEN-LAST:event_acaBotoesAddItesActionPerformed

    private void acaBotoesDelItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesDelItensActionPerformed
        acaTextfieldCodItens.setText("");
        acaTextfieldDes.setText("");
        acaMonetarioUnit.setValor(0.00);
        acaTextfieldQtde.setText("");
        acaComboProd.setSelectedIndex(0);
        acaMonetarioSubtot.setValor(0.00);
        if (!acaMonetarioSubtot.getValor().equals("") && tipoOperacao != INCLUINDO) {
            // calculaTotal();
        }
}//GEN-LAST:event_acaBotoesDelItensActionPerformed

    private void acaBotoesDelSelItenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesDelSelItenActionPerformed

        if (tipoOperacao == ALTERANDO) {
            JOptionPane.showMessageDialog(null, "altera");
            itenscotaper.setCotcod(Integer.parseInt(acaTextfieldCodigo.getText()));
            itenscotaper.setMatcod(Integer.parseInt(jTabela.dtm.getValueAt(jTabela.getSelectedRow(), 0).toString()));
            Conexao.executaSql(itenscotaper.getExcluiSql());
            jTabela.dtm.removeRow(jTabela.getSelectedRow());

        } else {

            jTabela.dtm.removeRow(jTabela.getSelectedRow());
            //acaMonetarioTotal.setValor(Double.parseDouble(calculaTotal(acaMonetarioUnit.getValor().toString())));

        }
}//GEN-LAST:event_acaBotoesDelSelItenActionPerformed
    public void addItem(AcaTabela tabela) {

        Object[] item = {acaTextfieldCodItens.getText(), acaTextfieldDes.getText().toUpperCase(), acaTextfieldQtde.getText(), acaMonetarioUnit.getText(), acaMonetarioSubtot.getText()};
        tabela.PrencheTabela(item);

    }
    private void acaBotoesConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesConsultarActionPerformed
        consultar();

}//GEN-LAST:event_acaBotoesConsultarActionPerformed

    private void acaBotoesIncuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesIncuirActionPerformed
        tipoOperacao = INCLUINDO;
        habilitarBotoes(true);
        habilitaCampos(true, camposPainel1);
    }//GEN-LAST:event_acaBotoesIncuirActionPerformed

    private void acaBotoesCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesCancelarActionPerformed
        cancelar();

}//GEN-LAST:event_acaBotoesCancelarActionPerformed

    private void acaComboTipoItensItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_acaComboTipoItensItemStateChanged
        if (acaComboTipoItens.getSelectedIndex() >= 0) {
            if (acaComboTipoItens.isPopupVisible()) {
                acaComboProd.buscaResult("select matcod, matnome from materiaprima where tipomatcod = " + acaComboTipoItens.getValor() + " ");
                acaComboFor.buscaResult("SELECT F1.FORCOD, F1.FONOME FROM FORNECEDOR F1, TIPOXFORNECEDOR T1 WHERE F1.FORCOD = T1.FORCOD and t1.tipomatcod = " + acaComboTipoItens.getValor() + "");
                habilitaCampos(true, camposPainel2);
                acaMonetarioSubtot.setValor(0.00);
                acaMonetarioUnit.setValor(0.00);
                acaTextfieldQtde.setText("");
            }
        }
    }//GEN-LAST:event_acaComboTipoItensItemStateChanged

    private void acaBotoesAddforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesAddforActionPerformed
        if (acaComboFor.getSelectedIndex() > 0) {
            if (!jTabelaFor.validaItens(acaComboFor.getValor())) {
                Object[] item = {acaTextfieldCodFor.getText(), acaComboFor.getSelectedItem()};
                jTabelaFor.PrencheTabela(item);
                acaComboFor.setSelectedIndex(0);
                acaTextfieldCodFor.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "ja existe o fornecedor na listagem abaixo");
                return;
            }
        }
    }//GEN-LAST:event_acaBotoesAddforActionPerformed

    private void acaComboForItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_acaComboForItemStateChanged
        if (acaComboFor.getSelectedIndex() > 0) {
            if (acaComboFor.isPopupVisible()) {
                acaTextfieldCodFor.setText(String.valueOf(acaComboFor.getValor()));

            } else {
                JOptionPane.showMessageDialog(null, "Ja existe o produto no pedido");
                acaComboFor.setSelectedIndex(0);
                return;
            }
        }
    }//GEN-LAST:event_acaComboForItemStateChanged

    private void acaBotoesDelForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesDelForActionPerformed
        if (tipoOperacao == ALTERANDO) {
            itenscotaper.setCotcod(Integer.parseInt(acaTextfieldCodigo.getText()));
            itenscotaper.setMatcod(Integer.parseInt(jTabela.dtm.getValueAt(jTabela.getSelectedRow(), 0).toString()));
            Conexao.executaSql(itenscotaper.getExcluiSql());
            jTabelaFor.dtm.removeRow(jTabelaFor.getSelectedRow());

        } else {
            jTabelaFor.dtm.removeRow(jTabelaFor.getSelectedRow());
            //acaMonetarioTotal.setValor(Double.parseDouble(calculaTotal(acaMonetarioUnit.getValor().toString())));

        }
    }//GEN-LAST:event_acaBotoesDelForActionPerformed

    private void acaBotoesConsulForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesConsulForActionPerformed
        if (telaconsultafor == null) {
            telaconsultafor = new TelaConsMov("Consulta Fornecedor ", this, new int[]{1, 2, 4}, new String[]{"Codigo", "Nome", "CPF/CNPJ"}, "fornecedor", "forcod", "fonome", "forcpf", "forcnpj");
            colu.add("CODIGO");
            colu.add("NOME");
            telaconsultafor.setColu(colu);
            telaconsultafor.addInternalFrameListener(this);
            TelaSistema.jdp.add(telaconsultafor);
            telaconsultafor.setVisible(true);
            tipoOperacao = PESQUISANDO;
        }
        TelaSistema.jdp.moveToFront(telaconsultafor);
    }//GEN-LAST:event_acaBotoesConsulForActionPerformed

    private void acaBotoesConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesConfirmarActionPerformed
        confirmar();
}//GEN-LAST:event_acaBotoesConfirmarActionPerformed

    private void acaBotoesExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaBotoesExcluirActionPerformed
        excluir();
}//GEN-LAST:event_acaBotoesExcluirActionPerformed

    private void acaComboTipoItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acaComboTipoItensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acaComboTipoItensActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.AcaBotoes acaBotoesAddItes;
    private componentes.AcaBotoes acaBotoesAddfor;
    protected componentes.AcaBotoes acaBotoesCancelar;
    public componentes.AcaBotoes acaBotoesConProd;
    protected componentes.AcaBotoes acaBotoesConfirmar;
    private componentes.AcaBotoes acaBotoesConsulFor;
    protected componentes.AcaBotoes acaBotoesConsultar;
    private componentes.AcaBotoes acaBotoesDelFor;
    private componentes.AcaBotoes acaBotoesDelItens;
    private componentes.AcaBotoes acaBotoesDelSelIten;
    protected componentes.AcaBotoes acaBotoesExcluir;
    protected componentes.AcaBotoes acaBotoesIncuir;
    public componentes.AcaBotoes acaBotoesNovoProd;
    private componentes.AcaCombo acaComboFor;
    public componentes.AcaCombo acaComboProd;
    private componentes.AcaCombo acaComboStatus;
    private componentes.AcaCombo acaComboTipoItens;
    private componentes.AcaData acaDataFin;
    private componentes.AcaData acaDataIni;
    private componentes.AcaLabel acaLabel1;
    private componentes.AcaLabel acaLabel10;
    private componentes.AcaLabel acaLabel11;
    private componentes.AcaLabel acaLabel12;
    private componentes.AcaLabel acaLabel2;
    private componentes.AcaLabel acaLabel3;
    private componentes.AcaLabel acaLabel4;
    private componentes.AcaLabel acaLabel5;
    private componentes.AcaLabel acaLabel6;
    private componentes.AcaLabel acaLabel7;
    private componentes.AcaLabel acaLabel8;
    private componentes.AcaLabel acaLabel9;
    public componentes.AcaLabel acaLabelSel;
    private componentes.AcaMonetario acaMonetarioSubtot;
    private componentes.AcaMonetario acaMonetarioUnit;
    private componentes.AcaTextfield acaTextfieldCodFor;
    protected componentes.AcaTextfield acaTextfieldCodItens;
    private componentes.AcaTextfield acaTextfieldCodigo;
    protected componentes.AcaTextfield acaTextfieldDes;
    private componentes.AcaTextfield acaTextfieldQtde;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneConsulta;
    private javax.swing.JScrollPane jScrollPaneFor;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void internalFrameOpened(InternalFrameEvent e) {
    }

    public void internalFrameClosing(InternalFrameEvent e) {
    }

    public void internalFrameClosed(InternalFrameEvent e) {
        if (e.getSource() == consultacotacao) {
            consultacotacao = null;
        }
        if (e.getSource() == telaconsultafor) {
            telaconsultafor = null;
        }
    }

    public void internalFrameIconified(InternalFrameEvent e) {
    }

    public void internalFrameDeiconified(InternalFrameEvent e) {
    }

    public void internalFrameActivated(InternalFrameEvent e) {
    }

    public void internalFrameDeactivated(InternalFrameEvent e) {
    }

    public void posicaoTela() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 200);
    }

    public void mouseClicked(MouseEvent e) {
        if (e.getClickCount() == 2) {
            int codigoCot = Integer.parseInt(jTabelaConsulta.getValueAt(jTabelaConsulta.getSelectedRow(), 0).toString());
            int codigoFor = Integer.parseInt(jTabelaConsulta.getValueAt(jTabelaConsulta.getSelectedRow(), 1).toString());
            if (consultacotacao == null) {
                consultacotacao = new ConsultaCotacao(codigoCot, codigoFor);
                consultacotacao.addInternalFrameListener(this);

                consultacotacao.setVisible(true);
                TelaSistema.jdp.add(consultacotacao);


            }
            TelaSistema.jdp.moveToFront(consultacotacao);

        }

    }

    public void mousePressed(MouseEvent e) {
    }

    public void mouseReleased(MouseEvent e) {
    }

    public void mouseEntered(MouseEvent e) {
    }

    public void mouseExited(MouseEvent e) {
    }

    private void excluir() {
        Object[] botoes = {"Sim", "Não"};
        int opcao = JOptionPane.showOptionDialog(null, " Deseja Excluir o cadastro ",
                "Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[0]);
        if (opcao == JOptionPane.YES_OPTION) {
            habilitarBotoes(true);
            habilitaCampos(false, camposPainel1);
            habilitaCampos(false, camposPainel2);
            habilitaCampos(false, camposPainel3);
            Conexao.executaSql("update cotfornecedor set codstatus = 0 where "
                    + "cotcod = " + Integer.parseInt((String) jTabelaConsulta.getValueAt(jTabelaConsulta.getSelectedRow(), 0)) + " and forcod = " + Integer.parseInt((String) jTabelaConsulta.getValueAt(jTabelaConsulta.getSelectedRow(), 1)) + "");



        }
        if (opcao == JOptionPane.NO_OPTION) {
            habilitaCampos(true, camposPainel1);

            return;

        }
        tipoOperacao = EXCLUINDO;

        habilitarBotoes(false);
    }

    public void cancelar() {
        limparCampos(camposPainel1);
        limparCampos(camposPainel2);
        limparCampos(camposPainel3);
        if(tipoOperacao == PESQUISANDO){
        jTabelaConsulta.limparPesquisa();
        }
        habilitaCampos(false, camposPainel1);
        habilitaCampos(false, camposPainel2);
        habilitaCampos(false, camposPainel3);
        tipoOperacao = PADRAO;
       
        habilitarBotoes(false);
    }
}
